set_property SRC_FILE_INFO {cfile:c:/Users/efree/Desktop/pointMLPWork/pointMLPWork.srcs/sources_1/bd/pmlp/ip/pmlp_FCL1_0_1/constraints/FCL1_ooc.xdc rfile:../../../pointMLPWork.srcs/sources_1/bd/pmlp/ip/pmlp_FCL1_0_1/constraints/FCL1_ooc.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AA15 [get_ports {s3_out_V_V_TDATA[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF19 [get_ports {s3_out_V_V_TDATA[52]}]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AB27 [get_ports {s_axi_control_RDATA[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF27 [get_ports {s_axi_control_RDATA[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AH29 [get_ports {s_axi_control_RDATA[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:8 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AJ29 [get_ports {s_axi_control_RDATA[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:9 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG27 [get_ports {s_axi_control_RDATA[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:10 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AB14 [get_ports {s3_out_V_V_TDATA[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:11 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF13 [get_ports {s3_out_V_V_TDATA[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:12 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AB16 [get_ports {s3_out_V_V_TDATA[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:13 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE13 [get_ports {s3_out_V_V_TDATA[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:14 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AK15 [get_ports {s3_out_V_V_TDATA[39]}]
set_property src_info {type:SCOPED_XDC file:1 line:15 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AJ18 [get_ports {s3_out_V_V_TDATA[45]}]
set_property src_info {type:SCOPED_XDC file:1 line:16 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN A3 [get_ports {input1_V_V_TDATA[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:17 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AA22 [get_ports ap_rst_n]
set_property src_info {type:SCOPED_XDC file:1 line:18 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE23 [get_ports interrupt]
set_property src_info {type:SCOPED_XDC file:1 line:19 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN R23 [get_ports {s_axi_control_WDATA[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:20 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE12 [get_ports {s3_out_V_V_TDATA[36]}]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AK13 [get_ports {s3_out_V_V_TDATA[48]}]
set_property src_info {type:SCOPED_XDC file:1 line:22 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AJ16 [get_ports {s3_out_V_V_TDATA[42]}]
set_property src_info {type:SCOPED_XDC file:1 line:23 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AA17 [get_ports {s3_out_V_V_TDATA[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:24 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AC22 [get_ports {s_axi_control_ARADDR[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:25 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF18 [get_ports {s3_out_V_V_TDATA[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:26 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AK16 [get_ports {s3_out_V_V_TDATA[41]}]
set_property src_info {type:SCOPED_XDC file:1 line:27 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AB21 [get_ports {s3_out_V_V_TDATA[50]}]
set_property src_info {type:SCOPED_XDC file:1 line:28 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AB19 [get_ports {s_axi_control_AWADDR[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:29 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AH27 [get_ports {s_axi_control_RDATA[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:30 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AA20 [get_ports {s_axi_control_RRESP[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG26 [get_ports {s_axi_control_RDATA[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:32 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN A2 [get_ports {input1_V_V_TDATA[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:33 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AD23 [get_ports ap_clk]
set_property src_info {type:SCOPED_XDC file:1 line:34 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AA24 [get_ports s3_out_V_V_TREADY]
set_property src_info {type:SCOPED_XDC file:1 line:35 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AD14 [get_ports {s3_out_V_V_TDATA[32]}]
set_property src_info {type:SCOPED_XDC file:1 line:36 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF12 [get_ports {s3_out_V_V_TDATA[35]}]
set_property src_info {type:SCOPED_XDC file:1 line:37 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AA13 [get_ports {s3_out_V_V_TDATA[49]}]
set_property src_info {type:SCOPED_XDC file:1 line:38 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG17 [get_ports {s3_out_V_V_TDATA[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:39 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE16 [get_ports {s3_out_V_V_TDATA[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:40 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AH17 [get_ports {s3_out_V_V_TDATA[38]}]
set_property src_info {type:SCOPED_XDC file:1 line:41 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AC12 [get_ports {s3_out_V_V_TDATA[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:42 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AC17 [get_ports {s3_out_V_V_TDATA[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:43 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AK30 [get_ports {s_axi_control_RDATA[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:44 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AH26 [get_ports {s_axi_control_RDATA[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:45 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF29 [get_ports {s_axi_control_RDATA[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:46 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE26 [get_ports {s_axi_control_RDATA[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:47 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN Y20 [get_ports {s_axi_control_RRESP[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:48 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AA25 [get_ports {s_axi_control_RDATA[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:49 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN A4 [get_ports {input1_V_V_TDATA[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE21 [get_ports s3_out_V_V_TVALID]
set_property src_info {type:SCOPED_XDC file:1 line:51 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AD21 [get_ports s_axi_control_ARREADY]
set_property src_info {type:SCOPED_XDC file:1 line:52 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN W21 [get_ports s_axi_control_RREADY]
set_property src_info {type:SCOPED_XDC file:1 line:53 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG25 [get_ports s_axi_control_RVALID]
set_property src_info {type:SCOPED_XDC file:1 line:54 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AK18 [get_ports {s3_out_V_V_TDATA[55]}]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN B2 [get_ports {input1_V_V_TDATA[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN B1 [get_ports {input1_V_V_TDATA[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AH18 [get_ports {s3_out_V_V_TDATA[46]}]
set_property src_info {type:SCOPED_XDC file:1 line:58 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AB15 [get_ports {s3_out_V_V_TDATA[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AC21 [get_ports {s_axi_control_ARADDR[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG30 [get_ports {s_axi_control_RDATA[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:61 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AC28 [get_ports {s_axi_control_RDATA[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:62 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AJ26 [get_ports {s_axi_control_RDATA[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:63 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG29 [get_ports {s_axi_control_RDATA[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:64 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AH12 [get_ports {s3_out_V_V_TDATA[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:65 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF15 [get_ports {s3_out_V_V_TDATA[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AC13 [get_ports {s3_out_V_V_TDATA[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:67 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AJ19 [get_ports {s3_out_V_V_TDATA[53]}]
set_property src_info {type:SCOPED_XDC file:1 line:68 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AB22 [get_ports s_axi_control_WVALID]
set_property src_info {type:SCOPED_XDC file:1 line:69 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE22 [get_ports input1_V_V_TREADY]
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN Y23 [get_ports s_axi_control_ARVALID]
set_property src_info {type:SCOPED_XDC file:1 line:71 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN Y21 [get_ports s_axi_control_BREADY]
set_property src_info {type:SCOPED_XDC file:1 line:72 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN V21 [get_ports {s_axi_control_WDATA[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:73 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE18 [get_ports {s3_out_V_V_TDATA[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:74 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN C2 [get_ports {input1_V_V_TDATA[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:75 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF22 [get_ports {s3_out_V_V_TDATA[63]}]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AH28 [get_ports {s_axi_control_RDATA[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:77 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE20 [get_ports {s_axi_control_AWADDR[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:78 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE28 [get_ports {s_axi_control_RDATA[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:79 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AD29 [get_ports {s_axi_control_RDATA[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:80 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE17 [get_ports {s3_out_V_V_TDATA[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:81 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AA14 [get_ports {s3_out_V_V_TDATA[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:82 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AD13 [get_ports {s3_out_V_V_TDATA[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AC16 [get_ports {s3_out_V_V_TDATA[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:84 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AC23 [get_ports {s_axi_control_ARADDR[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:85 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AK12 [get_ports {s3_out_V_V_TDATA[47]}]
set_property src_info {type:SCOPED_XDC file:1 line:86 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG19 [get_ports {s3_out_V_V_TDATA[51]}]
set_property src_info {type:SCOPED_XDC file:1 line:87 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AB24 [get_ports input1_V_V_TVALID]
set_property src_info {type:SCOPED_XDC file:1 line:88 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN Y22 [get_ports s_axi_control_AWVALID]
set_property src_info {type:SCOPED_XDC file:1 line:89 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG24 [get_ports s_axi_control_WREADY]
set_property src_info {type:SCOPED_XDC file:1 line:90 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN W24 [get_ports {s_axi_control_WDATA[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:91 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AA19 [get_ports {s_axi_control_WSTRB[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:92 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AD16 [get_ports {s3_out_V_V_TDATA[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:93 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AJ20 [get_ports {s3_out_V_V_TDATA[58]}]
set_property src_info {type:SCOPED_XDC file:1 line:94 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF14 [get_ports {s3_out_V_V_TDATA[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AD15 [get_ports {s3_out_V_V_TDATA[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:96 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE15 [get_ports {s3_out_V_V_TDATA[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:97 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AB17 [get_ports {s3_out_V_V_TDATA[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:98 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG14 [get_ports {s3_out_V_V_TDATA[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:99 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AK27 [get_ports {s_axi_control_RDATA[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:100 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AC19 [get_ports {s_axi_control_BRESP[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:101 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF25 [get_ports {s_axi_control_RDATA[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:102 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AJ30 [get_ports {s_axi_control_RDATA[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:103 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AJ28 [get_ports {s_axi_control_RDATA[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:104 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AK28 [get_ports {s_axi_control_RDATA[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:105 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE27 [get_ports {s_axi_control_RDATA[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:106 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AC18 [get_ports {s_axi_control_BRESP[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:107 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AK20 [get_ports {s3_out_V_V_TDATA[57]}]
set_property src_info {type:SCOPED_XDC file:1 line:108 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN C1 [get_ports {input1_V_V_TDATA[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:109 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AJ15 [get_ports {s3_out_V_V_TDATA[40]}]
set_property src_info {type:SCOPED_XDC file:1 line:110 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF20 [get_ports {s3_out_V_V_TDATA[60]}]
set_property src_info {type:SCOPED_XDC file:1 line:111 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG15 [get_ports {s3_out_V_V_TDATA[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:112 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AK17 [get_ports {s3_out_V_V_TDATA[56]}]
set_property src_info {type:SCOPED_XDC file:1 line:113 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AJ13 [get_ports {s3_out_V_V_TDATA[43]}]
set_property src_info {type:SCOPED_XDC file:1 line:114 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AC14 [get_ports {s3_out_V_V_TDATA[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:115 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF17 [get_ports {s3_out_V_V_TDATA[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:116 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AB20 [get_ports {s_axi_control_AWADDR[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:117 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AD28 [get_ports {s_axi_control_RDATA[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:118 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AC27 [get_ports {s_axi_control_RDATA[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:119 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF30 [get_ports {s_axi_control_RDATA[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:120 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AH14 [get_ports {s3_out_V_V_TDATA[34]}]
set_property src_info {type:SCOPED_XDC file:1 line:121 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN L4 [get_ports {input1_V_V_TDATA[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:122 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG21 [get_ports {s3_out_V_V_TDATA[62]}]
set_property src_info {type:SCOPED_XDC file:1 line:123 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AH21 [get_ports {s3_out_V_V_TDATA[61]}]
set_property src_info {type:SCOPED_XDC file:1 line:124 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF24 [get_ports s_axi_control_AWREADY]
set_property src_info {type:SCOPED_XDC file:1 line:125 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF23 [get_ports s_axi_control_BVALID]
set_property src_info {type:SCOPED_XDC file:1 line:126 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG20 [get_ports {s3_out_V_V_TDATA[59]}]
set_property src_info {type:SCOPED_XDC file:1 line:127 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AH13 [get_ports {s3_out_V_V_TDATA[33]}]
set_property src_info {type:SCOPED_XDC file:1 line:128 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG16 [get_ports {s3_out_V_V_TDATA[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AH16 [get_ports {s3_out_V_V_TDATA[37]}]
set_property src_info {type:SCOPED_XDC file:1 line:130 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AH19 [get_ports {s3_out_V_V_TDATA[54]}]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AA23 [get_ports {s_axi_control_ARADDR[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:132 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AF28 [get_ports {s_axi_control_RDATA[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:133 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AK26 [get_ports {s_axi_control_RDATA[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:134 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AD20 [get_ports {s_axi_control_AWADDR[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:135 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AD25 [get_ports {s_axi_control_RDATA[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:136 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AE25 [get_ports {s_axi_control_RDATA[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:137 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AJ14 [get_ports {s3_out_V_V_TDATA[44]}]
set_property src_info {type:SCOPED_XDC file:1 line:138 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AG12 [get_ports {s3_out_V_V_TDATA[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:139 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AB12 [get_ports {s3_out_V_V_TDATA[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:140 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN E2 [get_ports {input1_V_V_TDATA[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:141 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN K12 [get_ports {input1_V_V_TDATA[51]}]
set_property src_info {type:SCOPED_XDC file:1 line:142 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN J10 [get_ports {input1_V_V_TDATA[60]}]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN T23 [get_ports {s_axi_control_WDATA[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:144 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN E6 [get_ports {input1_V_V_TDATA[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:145 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN J5 [get_ports {input1_V_V_TDATA[39]}]
set_property src_info {type:SCOPED_XDC file:1 line:146 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN E1 [get_ports {input1_V_V_TDATA[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:147 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN K6 [get_ports {input1_V_V_TDATA[38]}]
set_property src_info {type:SCOPED_XDC file:1 line:148 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN W25 [get_ports {s_axi_control_WDATA[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:149 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN P23 [get_ports {s_axi_control_WDATA[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:150 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN R27 [get_ports {s_axi_control_WDATA[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:151 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN G1 [get_ports {input1_V_V_TDATA[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:152 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AA18 [get_ports {s_axi_control_WSTRB[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:153 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN G2 [get_ports {input1_V_V_TDATA[36]}]
set_property src_info {type:SCOPED_XDC file:1 line:154 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN L9 [get_ports {input1_V_V_TDATA[53]}]
set_property src_info {type:SCOPED_XDC file:1 line:155 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN J9 [get_ports {input1_V_V_TDATA[59]}]
set_property src_info {type:SCOPED_XDC file:1 line:156 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN L10 [get_ports {input1_V_V_TDATA[54]}]
set_property src_info {type:SCOPED_XDC file:1 line:157 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN N27 [get_ports {s_axi_control_WDATA[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:158 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN U27 [get_ports {s_axi_control_WDATA[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:159 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN C3 [get_ports {input1_V_V_TDATA[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:160 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN K1 [get_ports {input1_V_V_TDATA[45]}]
set_property src_info {type:SCOPED_XDC file:1 line:161 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN H6 [get_ports {input1_V_V_TDATA[34]}]
set_property src_info {type:SCOPED_XDC file:1 line:162 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN L3 [get_ports {input1_V_V_TDATA[42]}]
set_property src_info {type:SCOPED_XDC file:1 line:163 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN V22 [get_ports {s_axi_control_WDATA[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:164 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN V23 [get_ports {s_axi_control_WDATA[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:165 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AD18 [get_ports {s_axi_control_WSTRB[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:166 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN F5 [get_ports {input1_V_V_TDATA[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:167 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN K7 [get_ports {input1_V_V_TDATA[61]}]
set_property src_info {type:SCOPED_XDC file:1 line:168 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN L8 [get_ports {input1_V_V_TDATA[58]}]
set_property src_info {type:SCOPED_XDC file:1 line:169 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN J4 [get_ports {input1_V_V_TDATA[48]}]
set_property src_info {type:SCOPED_XDC file:1 line:170 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN R26 [get_ports {s_axi_control_WDATA[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:171 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN V26 [get_ports {s_axi_control_WDATA[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:172 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN E3 [get_ports {input1_V_V_TDATA[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN L2 [get_ports {input1_V_V_TDATA[41]}]
set_property src_info {type:SCOPED_XDC file:1 line:174 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN F2 [get_ports {input1_V_V_TDATA[35]}]
set_property src_info {type:SCOPED_XDC file:1 line:175 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN H3 [get_ports {input1_V_V_TDATA[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:176 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN K10 [get_ports {input1_V_V_TDATA[55]}]
set_property src_info {type:SCOPED_XDC file:1 line:177 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN K8 [get_ports {input1_V_V_TDATA[57]}]
set_property src_info {type:SCOPED_XDC file:1 line:178 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN K3 [get_ports {input1_V_V_TDATA[44]}]
set_property src_info {type:SCOPED_XDC file:1 line:179 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN A5 [get_ports {input1_V_V_TDATA[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:180 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN J1 [get_ports {input1_V_V_TDATA[32]}]
set_property src_info {type:SCOPED_XDC file:1 line:181 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN T25 [get_ports {s_axi_control_WDATA[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:182 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN P26 [get_ports {s_axi_control_WDATA[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:183 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN R22 [get_ports {s_axi_control_WDATA[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:184 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN V24 [get_ports {s_axi_control_WDATA[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:185 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN F3 [get_ports {input1_V_V_TDATA[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:186 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN K5 [get_ports {input1_V_V_TDATA[40]}]
set_property src_info {type:SCOPED_XDC file:1 line:187 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN D3 [get_ports {input1_V_V_TDATA[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:188 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN U26 [get_ports {s_axi_control_WDATA[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:189 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN R25 [get_ports {s_axi_control_WDATA[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:190 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN N26 [get_ports {s_axi_control_WDATA[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:191 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN W28 [get_ports {s_axi_control_WDATA[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:192 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN J6 [get_ports {input1_V_V_TDATA[37]}]
set_property src_info {type:SCOPED_XDC file:1 line:193 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN G6 [get_ports {input1_V_V_TDATA[33]}]
set_property src_info {type:SCOPED_XDC file:1 line:194 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN C4 [get_ports {input1_V_V_TDATA[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:195 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN T22 [get_ports {s_axi_control_WDATA[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:196 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN L5 [get_ports {input1_V_V_TDATA[49]}]
set_property src_info {type:SCOPED_XDC file:1 line:197 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN G7 [get_ports {input1_V_V_TDATA[63]}]
set_property src_info {type:SCOPED_XDC file:1 line:198 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN L7 [get_ports {input1_V_V_TDATA[62]}]
set_property src_info {type:SCOPED_XDC file:1 line:199 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN B4 [get_ports {input1_V_V_TDATA[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:200 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN D1 [get_ports {input1_V_V_TDATA[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:201 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN D5 [get_ports {input1_V_V_TDATA[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:202 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN L12 [get_ports {input1_V_V_TDATA[52]}]
set_property src_info {type:SCOPED_XDC file:1 line:203 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN B5 [get_ports {input1_V_V_TDATA[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:204 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN D4 [get_ports {input1_V_V_TDATA[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:205 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN U22 [get_ports {s_axi_control_WDATA[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:206 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN U24 [get_ports {s_axi_control_WDATA[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:207 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN L1 [get_ports {input1_V_V_TDATA[46]}]
set_property src_info {type:SCOPED_XDC file:1 line:208 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN K11 [get_ports {input1_V_V_TDATA[56]}]
set_property src_info {type:SCOPED_XDC file:1 line:209 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN J3 [get_ports {input1_V_V_TDATA[47]}]
set_property src_info {type:SCOPED_XDC file:1 line:210 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN W26 [get_ports {s_axi_control_WDATA[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:211 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN R21 [get_ports {s_axi_control_WDATA[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:212 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN P24 [get_ports {s_axi_control_WDATA[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:213 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN T27 [get_ports {s_axi_control_WDATA[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:214 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN G4 [get_ports {input1_V_V_TDATA[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:215 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN H4 [get_ports {input1_V_V_TDATA[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:216 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN AD19 [get_ports {s_axi_control_WSTRB[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:217 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN G5 [get_ports {input1_V_V_TDATA[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:218 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN M10 [get_ports {input1_V_V_TDATA[50]}]
set_property src_info {type:SCOPED_XDC file:1 line:219 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN E5 [get_ports {input1_V_V_TDATA[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:220 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN F4 [get_ports {input1_V_V_TDATA[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:221 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN K2 [get_ports {input1_V_V_TDATA[43]}]
set_property src_info {type:SCOPED_XDC file:1 line:222 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN H1 [get_ports {input1_V_V_TDATA[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:223 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN H2 [get_ports {input1_V_V_TDATA[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:224 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN P25 [get_ports {s_axi_control_WDATA[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:225 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN T24 [get_ports {s_axi_control_WDATA[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:226 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN P21 [get_ports {s_axi_control_WDATA[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:227 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property PACKAGE_PIN U25 [get_ports {s_axi_control_WDATA[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:297 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[0]}]
set_property src_info {type:SCOPED_XDC file:1 line:298 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[10]}]
set_property src_info {type:SCOPED_XDC file:1 line:299 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[11]}]
set_property src_info {type:SCOPED_XDC file:1 line:300 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[12]}]
set_property src_info {type:SCOPED_XDC file:1 line:301 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[13]}]
set_property src_info {type:SCOPED_XDC file:1 line:302 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[14]}]
set_property src_info {type:SCOPED_XDC file:1 line:303 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[15]}]
set_property src_info {type:SCOPED_XDC file:1 line:304 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[16]}]
set_property src_info {type:SCOPED_XDC file:1 line:305 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[17]}]
set_property src_info {type:SCOPED_XDC file:1 line:306 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[18]}]
set_property src_info {type:SCOPED_XDC file:1 line:307 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[19]}]
set_property src_info {type:SCOPED_XDC file:1 line:308 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[1]}]
set_property src_info {type:SCOPED_XDC file:1 line:309 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[20]}]
set_property src_info {type:SCOPED_XDC file:1 line:310 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[21]}]
set_property src_info {type:SCOPED_XDC file:1 line:311 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[22]}]
set_property src_info {type:SCOPED_XDC file:1 line:312 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[23]}]
set_property src_info {type:SCOPED_XDC file:1 line:313 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[24]}]
set_property src_info {type:SCOPED_XDC file:1 line:314 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[25]}]
set_property src_info {type:SCOPED_XDC file:1 line:315 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[26]}]
set_property src_info {type:SCOPED_XDC file:1 line:316 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[27]}]
set_property src_info {type:SCOPED_XDC file:1 line:317 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[28]}]
set_property src_info {type:SCOPED_XDC file:1 line:318 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[29]}]
set_property src_info {type:SCOPED_XDC file:1 line:319 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[2]}]
set_property src_info {type:SCOPED_XDC file:1 line:320 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[30]}]
set_property src_info {type:SCOPED_XDC file:1 line:321 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[31]}]
set_property src_info {type:SCOPED_XDC file:1 line:322 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[32]}]
set_property src_info {type:SCOPED_XDC file:1 line:323 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[33]}]
set_property src_info {type:SCOPED_XDC file:1 line:324 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[34]}]
set_property src_info {type:SCOPED_XDC file:1 line:325 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[35]}]
set_property src_info {type:SCOPED_XDC file:1 line:326 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[36]}]
set_property src_info {type:SCOPED_XDC file:1 line:327 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[37]}]
set_property src_info {type:SCOPED_XDC file:1 line:328 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[38]}]
set_property src_info {type:SCOPED_XDC file:1 line:329 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[39]}]
set_property src_info {type:SCOPED_XDC file:1 line:330 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[3]}]
set_property src_info {type:SCOPED_XDC file:1 line:331 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[40]}]
set_property src_info {type:SCOPED_XDC file:1 line:332 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[41]}]
set_property src_info {type:SCOPED_XDC file:1 line:333 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[42]}]
set_property src_info {type:SCOPED_XDC file:1 line:334 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[43]}]
set_property src_info {type:SCOPED_XDC file:1 line:335 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[44]}]
set_property src_info {type:SCOPED_XDC file:1 line:336 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[45]}]
set_property src_info {type:SCOPED_XDC file:1 line:337 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[46]}]
set_property src_info {type:SCOPED_XDC file:1 line:338 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[47]}]
set_property src_info {type:SCOPED_XDC file:1 line:339 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[48]}]
set_property src_info {type:SCOPED_XDC file:1 line:340 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[49]}]
set_property src_info {type:SCOPED_XDC file:1 line:341 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[4]}]
set_property src_info {type:SCOPED_XDC file:1 line:342 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[50]}]
set_property src_info {type:SCOPED_XDC file:1 line:343 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[51]}]
set_property src_info {type:SCOPED_XDC file:1 line:344 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[52]}]
set_property src_info {type:SCOPED_XDC file:1 line:345 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[53]}]
set_property src_info {type:SCOPED_XDC file:1 line:346 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[54]}]
set_property src_info {type:SCOPED_XDC file:1 line:347 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[55]}]
set_property src_info {type:SCOPED_XDC file:1 line:348 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[56]}]
set_property src_info {type:SCOPED_XDC file:1 line:349 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[57]}]
set_property src_info {type:SCOPED_XDC file:1 line:350 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[58]}]
set_property src_info {type:SCOPED_XDC file:1 line:351 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[59]}]
set_property src_info {type:SCOPED_XDC file:1 line:352 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[5]}]
set_property src_info {type:SCOPED_XDC file:1 line:353 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[60]}]
set_property src_info {type:SCOPED_XDC file:1 line:354 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[61]}]
set_property src_info {type:SCOPED_XDC file:1 line:355 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[62]}]
set_property src_info {type:SCOPED_XDC file:1 line:356 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[63]}]
set_property src_info {type:SCOPED_XDC file:1 line:357 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[6]}]
set_property src_info {type:SCOPED_XDC file:1 line:358 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[7]}]
set_property src_info {type:SCOPED_XDC file:1 line:359 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[8]}]
set_property src_info {type:SCOPED_XDC file:1 line:360 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {s3_out_V_V_TDATA[9]}]
set_property src_info {type:SCOPED_XDC file:1 line:361 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports s3_out_V_V_TREADY]
set_property src_info {type:SCOPED_XDC file:1 line:362 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports s3_out_V_V_TVALID]
