// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Conv1DMac_new (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        in_V_V_dout,
        in_V_V_empty_n,
        in_V_V_read,
        out_V_V_din,
        out_V_V_full_n,
        out_V_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state7 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] in_V_V_dout;
input   in_V_V_empty_n;
output   in_V_V_read;
output  [31:0] out_V_V_din;
input   out_V_V_full_n;
output   out_V_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg in_V_V_read;
reg out_V_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [13:0] weights19_m_weights_3_address0;
reg    weights19_m_weights_3_ce0;
wire   [5:0] weights19_m_weights_3_q0;
wire   [13:0] weights19_m_weights_2_address0;
reg    weights19_m_weights_2_ce0;
wire   [5:0] weights19_m_weights_2_q0;
wire   [13:0] weights19_m_weights_1_address0;
reg    weights19_m_weights_1_ce0;
wire   [5:0] weights19_m_weights_1_q0;
wire   [13:0] weights19_m_weights_s_address0;
reg    weights19_m_weights_s_ce0;
wire   [5:0] weights19_m_weights_s_q0;
reg    in_V_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_flatten_reg_1477;
reg   [0:0] exitcond_flatten_reg_1477_pp0_iter1_reg;
reg    out_V_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] tmp_162_reg_1504;
reg   [0:0] tmp_162_reg_1504_pp0_iter3_reg;
reg   [20:0] indvar_flatten4_reg_241;
reg   [15:0] indvar_flatten_reg_252;
reg   [6:0] nm_reg_263;
reg   [8:0] sf_reg_274;
wire   [0:0] exitcond_flatten_fu_317_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_state6_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
wire   [20:0] indvar_flatten_next1_fu_323_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [5:0] nm_t_mid2_fu_417_p3;
reg   [5:0] nm_t_mid2_reg_1486;
reg   [5:0] nm_t_mid2_reg_1486_pp0_iter1_reg;
reg   [5:0] nm_t_mid2_reg_1486_pp0_iter2_reg;
wire   [6:0] nm_mid2_fu_425_p3;
wire   [13:0] tmp_142_fu_437_p2;
reg   [13:0] tmp_142_reg_1499;
wire   [0:0] tmp_162_fu_443_p2;
reg   [0:0] tmp_162_reg_1504_pp0_iter1_reg;
reg   [0:0] tmp_162_reg_1504_pp0_iter2_reg;
wire   [8:0] sf_1_fu_449_p2;
wire   [15:0] indvar_flatten_next_fu_461_p3;
reg   [6:0] tmp_97_reg_1538;
reg   [0:0] tmp_1023_reg_1543;
wire   [0:0] tmp_163_fu_544_p2;
reg   [0:0] tmp_163_reg_1548;
reg   [6:0] tmp_100_reg_1553;
reg   [0:0] tmp_1026_reg_1558;
wire   [0:0] tmp_255_1_fu_614_p2;
reg   [0:0] tmp_255_1_reg_1563;
reg   [6:0] tmp_103_reg_1568;
reg   [0:0] tmp_1029_reg_1573;
wire   [0:0] tmp_255_2_fu_684_p2;
reg   [0:0] tmp_255_2_reg_1578;
reg   [6:0] tmp_106_reg_1583;
reg   [0:0] tmp_1032_reg_1588;
wire   [0:0] tmp_255_3_fu_754_p2;
reg   [0:0] tmp_255_3_reg_1593;
wire   [7:0] p_Val2_s_fu_1017_p2;
reg   [7:0] p_Val2_s_reg_1598;
wire   [7:0] p_Val2_21_1_fu_1156_p2;
reg   [7:0] p_Val2_21_1_reg_1603;
wire   [7:0] p_Val2_21_2_fu_1295_p2;
reg   [7:0] p_Val2_21_2_reg_1608;
wire   [7:0] p_Val2_21_3_fu_1434_p2;
reg   [7:0] p_Val2_21_3_reg_1613;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter3;
wire   [63:0] tmp_145_fu_469_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] macRegisters_0_V_9_fu_160;
wire   [7:0] macRegisters_0_V_fu_789_p2;
reg   [7:0] macRegisters_1_V_9_fu_164;
wire   [7:0] macRegisters_1_V_fu_812_p2;
reg   [7:0] macRegisters_2_V_9_fu_168;
wire   [7:0] macRegisters_2_V_fu_835_p2;
reg   [7:0] macRegisters_3_V_9_fu_172;
wire   [7:0] macRegisters_3_V_fu_858_p2;
wire   [5:0] tmp_fu_305_p1;
wire   [0:0] exitcond_flatten4_fu_329_p2;
wire   [13:0] tmp_140_fu_309_p3;
wire   [0:0] tmp_s_fu_365_p2;
wire   [0:0] not_exitcond_flatten_fu_359_p2;
wire   [6:0] nm_mid_fu_335_p3;
wire   [0:0] tmp_141_mid_fu_371_p2;
wire   [0:0] tmp_867_fu_383_p2;
wire   [6:0] nm_1_fu_377_p2;
wire   [5:0] tmp_1021_fu_397_p1;
wire   [13:0] tmp_140_mid1_fu_401_p3;
wire   [13:0] tmp_140_mid_fu_343_p3;
wire   [5:0] nm_t_mid_fu_351_p3;
wire   [8:0] sf_mid2_fu_389_p3;
wire   [13:0] sf_cast1_fu_433_p1;
wire   [13:0] tmp_140_mid2_fu_409_p3;
wire   [15:0] indvar_flatten_op_fu_455_p2;
wire  signed [5:0] p_Val2_s_191_fu_484_p0;
wire  signed [7:0] p_Val2_s_191_fu_484_p1;
wire  signed [13:0] p_08_cast_cast_fu_476_p1;
wire   [13:0] p_Val2_s_191_fu_484_p2;
wire   [0:0] tmp_1024_fu_516_p1;
wire   [0:0] tmp_1022_fu_490_p3;
wire   [4:0] tmp_148_fu_526_p4;
wire   [0:0] tmp_147_fu_520_p2;
wire   [5:0] tmp_149_fu_536_p3;
wire  signed [5:0] p_Val2_1_fu_554_p0;
wire  signed [7:0] p_Val2_1_fu_554_p1;
wire   [13:0] p_Val2_1_fu_554_p2;
wire   [0:0] tmp_1027_fu_586_p1;
wire   [0:0] tmp_1025_fu_560_p3;
wire   [4:0] tmp_152_fu_596_p4;
wire   [0:0] tmp_151_fu_590_p2;
wire   [5:0] tmp_153_fu_606_p3;
wire  signed [5:0] p_Val2_2_fu_624_p0;
wire  signed [7:0] p_Val2_2_fu_624_p1;
wire   [13:0] p_Val2_2_fu_624_p2;
wire   [0:0] tmp_1030_fu_656_p1;
wire   [0:0] tmp_1028_fu_630_p3;
wire   [4:0] tmp_156_fu_666_p4;
wire   [0:0] tmp_155_fu_660_p2;
wire   [5:0] tmp_157_fu_676_p3;
wire  signed [5:0] p_Val2_3_fu_694_p0;
wire  signed [7:0] p_Val2_3_fu_694_p1;
wire   [13:0] p_Val2_3_fu_694_p2;
wire   [0:0] tmp_1033_fu_726_p1;
wire   [0:0] tmp_1031_fu_700_p3;
wire   [4:0] tmp_160_fu_736_p4;
wire   [0:0] tmp_159_fu_730_p2;
wire   [5:0] tmp_161_fu_746_p3;
wire   [0:0] qb_assign_1_fu_775_p2;
wire   [7:0] tmp_164_fu_779_p1;
wire  signed [7:0] tmp_98_fu_772_p1;
wire   [7:0] tmp1_fu_783_p2;
wire   [0:0] qb_assign_1_1_fu_798_p2;
wire   [7:0] tmp_256_1_fu_802_p1;
wire  signed [7:0] tmp_101_fu_795_p1;
wire   [7:0] tmp2_fu_806_p2;
wire   [0:0] qb_assign_1_2_fu_821_p2;
wire   [7:0] tmp_256_2_fu_825_p1;
wire  signed [7:0] tmp_104_fu_818_p1;
wire   [7:0] tmp3_fu_829_p2;
wire   [0:0] qb_assign_1_3_fu_844_p2;
wire   [7:0] tmp_256_3_fu_848_p1;
wire  signed [7:0] tmp_107_fu_841_p1;
wire   [7:0] tmp4_fu_852_p2;
wire   [7:0] tmp_108_fu_884_p66;
wire   [7:0] tmp_109_fu_1023_p66;
wire   [7:0] tmp_110_fu_1162_p66;
wire   [7:0] tmp_111_fu_1301_p66;
wire    ap_CS_fsm_state7;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

Conv1DMac_new_weibak #(
    .DataWidth( 6 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
weights19_m_weights_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights19_m_weights_3_address0),
    .ce0(weights19_m_weights_3_ce0),
    .q0(weights19_m_weights_3_q0)
);

Conv1DMac_new_weibbk #(
    .DataWidth( 6 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
weights19_m_weights_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights19_m_weights_2_address0),
    .ce0(weights19_m_weights_2_ce0),
    .q0(weights19_m_weights_2_q0)
);

Conv1DMac_new_weibck #(
    .DataWidth( 6 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
weights19_m_weights_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights19_m_weights_1_address0),
    .ce0(weights19_m_weights_1_ce0),
    .q0(weights19_m_weights_1_q0)
);

Conv1DMac_new_weibdk #(
    .DataWidth( 6 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
weights19_m_weights_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(weights19_m_weights_s_address0),
    .ce0(weights19_m_weights_s_ce0),
    .q0(weights19_m_weights_s_q0)
);

computeS3_mux_646yd2_x_x_x_x_x_x_x_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
computeS3_mux_646yd2_x_x_x_x_x_x_x_x_U202(
    .din0(8'd0),
    .din1(8'd7),
    .din2(8'd254),
    .din3(8'd0),
    .din4(8'd2),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd0),
    .din8(8'd5),
    .din9(8'd3),
    .din10(8'd254),
    .din11(8'd10),
    .din12(8'd6),
    .din13(8'd0),
    .din14(8'd0),
    .din15(8'd0),
    .din16(8'd0),
    .din17(8'd1),
    .din18(8'd0),
    .din19(8'd0),
    .din20(8'd3),
    .din21(8'd0),
    .din22(8'd0),
    .din23(8'd1),
    .din24(8'd11),
    .din25(8'd13),
    .din26(8'd1),
    .din27(8'd0),
    .din28(8'd13),
    .din29(8'd15),
    .din30(8'd0),
    .din31(8'd2),
    .din32(8'd4),
    .din33(8'd4),
    .din34(8'd1),
    .din35(8'd0),
    .din36(8'd8),
    .din37(8'd17),
    .din38(8'd8),
    .din39(8'd0),
    .din40(8'd254),
    .din41(8'd255),
    .din42(8'd0),
    .din43(8'd0),
    .din44(8'd3),
    .din45(8'd0),
    .din46(8'd8),
    .din47(8'd1),
    .din48(8'd0),
    .din49(8'd1),
    .din50(8'd0),
    .din51(8'd13),
    .din52(8'd0),
    .din53(8'd0),
    .din54(8'd8),
    .din55(8'd0),
    .din56(8'd0),
    .din57(8'd253),
    .din58(8'd0),
    .din59(8'd0),
    .din60(8'd0),
    .din61(8'd10),
    .din62(8'd248),
    .din63(8'd4),
    .din64(nm_t_mid2_reg_1486_pp0_iter2_reg),
    .dout(tmp_108_fu_884_p66)
);

computeS3_mux_646yd2_x_x_x_x_x_x_x_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
computeS3_mux_646yd2_x_x_x_x_x_x_x_x_U203(
    .din0(8'd0),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(8'd0),
    .din5(8'd6),
    .din6(8'd0),
    .din7(8'd7),
    .din8(8'd2),
    .din9(8'd0),
    .din10(8'd0),
    .din11(8'd255),
    .din12(8'd0),
    .din13(8'd1),
    .din14(8'd0),
    .din15(8'd0),
    .din16(8'd16),
    .din17(8'd9),
    .din18(8'd0),
    .din19(8'd0),
    .din20(8'd25),
    .din21(8'd0),
    .din22(8'd11),
    .din23(8'd255),
    .din24(8'd0),
    .din25(8'd6),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd8),
    .din29(8'd1),
    .din30(8'd10),
    .din31(8'd254),
    .din32(8'd0),
    .din33(8'd21),
    .din34(8'd5),
    .din35(8'd0),
    .din36(8'd1),
    .din37(8'd0),
    .din38(8'd19),
    .din39(8'd14),
    .din40(8'd10),
    .din41(8'd0),
    .din42(8'd0),
    .din43(8'd0),
    .din44(8'd21),
    .din45(8'd0),
    .din46(8'd0),
    .din47(8'd0),
    .din48(8'd0),
    .din49(8'd0),
    .din50(8'd0),
    .din51(8'd255),
    .din52(8'd6),
    .din53(8'd17),
    .din54(8'd0),
    .din55(8'd0),
    .din56(8'd10),
    .din57(8'd254),
    .din58(8'd6),
    .din59(8'd12),
    .din60(8'd13),
    .din61(8'd0),
    .din62(8'd254),
    .din63(8'd0),
    .din64(nm_t_mid2_reg_1486_pp0_iter2_reg),
    .dout(tmp_109_fu_1023_p66)
);

computeS3_mux_646yd2_x_x_x_x_x_x_x_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
computeS3_mux_646yd2_x_x_x_x_x_x_x_x_U204(
    .din0(8'd10),
    .din1(8'd1),
    .din2(8'd2),
    .din3(8'd18),
    .din4(8'd16),
    .din5(8'd0),
    .din6(8'd0),
    .din7(8'd11),
    .din8(8'd0),
    .din9(8'd20),
    .din10(8'd0),
    .din11(8'd0),
    .din12(8'd255),
    .din13(8'd17),
    .din14(8'd0),
    .din15(8'd0),
    .din16(8'd0),
    .din17(8'd14),
    .din18(8'd17),
    .din19(8'd0),
    .din20(8'd3),
    .din21(8'd0),
    .din22(8'd20),
    .din23(8'd0),
    .din24(8'd1),
    .din25(8'd5),
    .din26(8'd7),
    .din27(8'd253),
    .din28(8'd0),
    .din29(8'd0),
    .din30(8'd0),
    .din31(8'd0),
    .din32(8'd10),
    .din33(8'd241),
    .din34(8'd2),
    .din35(8'd0),
    .din36(8'd11),
    .din37(8'd0),
    .din38(8'd0),
    .din39(8'd0),
    .din40(8'd4),
    .din41(8'd2),
    .din42(8'd248),
    .din43(8'd8),
    .din44(8'd0),
    .din45(8'd0),
    .din46(8'd7),
    .din47(8'd11),
    .din48(8'd0),
    .din49(8'd0),
    .din50(8'd0),
    .din51(8'd15),
    .din52(8'd247),
    .din53(8'd0),
    .din54(8'd0),
    .din55(8'd0),
    .din56(8'd252),
    .din57(8'd14),
    .din58(8'd11),
    .din59(8'd0),
    .din60(8'd0),
    .din61(8'd10),
    .din62(8'd8),
    .din63(8'd0),
    .din64(nm_t_mid2_reg_1486_pp0_iter2_reg),
    .dout(tmp_110_fu_1162_p66)
);

computeS3_mux_646yd2_x_x_x_x_x_x_x_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 8 ),
    .din11_WIDTH( 8 ),
    .din12_WIDTH( 8 ),
    .din13_WIDTH( 8 ),
    .din14_WIDTH( 8 ),
    .din15_WIDTH( 8 ),
    .din16_WIDTH( 8 ),
    .din17_WIDTH( 8 ),
    .din18_WIDTH( 8 ),
    .din19_WIDTH( 8 ),
    .din20_WIDTH( 8 ),
    .din21_WIDTH( 8 ),
    .din22_WIDTH( 8 ),
    .din23_WIDTH( 8 ),
    .din24_WIDTH( 8 ),
    .din25_WIDTH( 8 ),
    .din26_WIDTH( 8 ),
    .din27_WIDTH( 8 ),
    .din28_WIDTH( 8 ),
    .din29_WIDTH( 8 ),
    .din30_WIDTH( 8 ),
    .din31_WIDTH( 8 ),
    .din32_WIDTH( 8 ),
    .din33_WIDTH( 8 ),
    .din34_WIDTH( 8 ),
    .din35_WIDTH( 8 ),
    .din36_WIDTH( 8 ),
    .din37_WIDTH( 8 ),
    .din38_WIDTH( 8 ),
    .din39_WIDTH( 8 ),
    .din40_WIDTH( 8 ),
    .din41_WIDTH( 8 ),
    .din42_WIDTH( 8 ),
    .din43_WIDTH( 8 ),
    .din44_WIDTH( 8 ),
    .din45_WIDTH( 8 ),
    .din46_WIDTH( 8 ),
    .din47_WIDTH( 8 ),
    .din48_WIDTH( 8 ),
    .din49_WIDTH( 8 ),
    .din50_WIDTH( 8 ),
    .din51_WIDTH( 8 ),
    .din52_WIDTH( 8 ),
    .din53_WIDTH( 8 ),
    .din54_WIDTH( 8 ),
    .din55_WIDTH( 8 ),
    .din56_WIDTH( 8 ),
    .din57_WIDTH( 8 ),
    .din58_WIDTH( 8 ),
    .din59_WIDTH( 8 ),
    .din60_WIDTH( 8 ),
    .din61_WIDTH( 8 ),
    .din62_WIDTH( 8 ),
    .din63_WIDTH( 8 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
computeS3_mux_646yd2_x_x_x_x_x_x_x_x_U205(
    .din0(8'd254),
    .din1(8'd9),
    .din2(8'd1),
    .din3(8'd20),
    .din4(8'd0),
    .din5(8'd6),
    .din6(8'd255),
    .din7(8'd0),
    .din8(8'd0),
    .din9(8'd0),
    .din10(8'd0),
    .din11(8'd0),
    .din12(8'd2),
    .din13(8'd14),
    .din14(8'd0),
    .din15(8'd0),
    .din16(8'd0),
    .din17(8'd14),
    .din18(8'd12),
    .din19(8'd14),
    .din20(8'd0),
    .din21(8'd2),
    .din22(8'd3),
    .din23(8'd0),
    .din24(8'd0),
    .din25(8'd1),
    .din26(8'd0),
    .din27(8'd0),
    .din28(8'd0),
    .din29(8'd9),
    .din30(8'd8),
    .din31(8'd5),
    .din32(8'd0),
    .din33(8'd12),
    .din34(8'd3),
    .din35(8'd0),
    .din36(8'd7),
    .din37(8'd17),
    .din38(8'd0),
    .din39(8'd0),
    .din40(8'd9),
    .din41(8'd6),
    .din42(8'd0),
    .din43(8'd0),
    .din44(8'd0),
    .din45(8'd3),
    .din46(8'd0),
    .din47(8'd10),
    .din48(8'd0),
    .din49(8'd0),
    .din50(8'd0),
    .din51(8'd9),
    .din52(8'd12),
    .din53(8'd6),
    .din54(8'd0),
    .din55(8'd0),
    .din56(8'd11),
    .din57(8'd255),
    .din58(8'd0),
    .din59(8'd11),
    .din60(8'd17),
    .din61(8'd3),
    .din62(8'd0),
    .din63(8'd0),
    .din64(nm_t_mid2_reg_1486_pp0_iter2_reg),
    .dout(tmp_111_fu_1301_p66)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_317_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten4_reg_241 <= indvar_flatten_next1_fu_323_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten4_reg_241 <= 21'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_317_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_252 <= indvar_flatten_next_fu_461_p3;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_252 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_162_reg_1504_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        macRegisters_0_V_9_fu_160 <= macRegisters_0_V_fu_789_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_162_reg_1504_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        macRegisters_0_V_9_fu_160 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_162_reg_1504_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        macRegisters_1_V_9_fu_164 <= macRegisters_1_V_fu_812_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_162_reg_1504_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        macRegisters_1_V_9_fu_164 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_162_reg_1504_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        macRegisters_2_V_9_fu_168 <= macRegisters_2_V_fu_835_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_162_reg_1504_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        macRegisters_2_V_9_fu_168 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_162_reg_1504_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        macRegisters_3_V_9_fu_172 <= macRegisters_3_V_fu_858_p2;
    end else if (((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)) | ((tmp_162_reg_1504_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        macRegisters_3_V_9_fu_172 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_317_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nm_reg_263 <= nm_mid2_fu_425_p3;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        nm_reg_263 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_317_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sf_reg_274 <= sf_1_fu_449_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        sf_reg_274 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_flatten_reg_1477 <= exitcond_flatten_fu_317_p2;
        exitcond_flatten_reg_1477_pp0_iter1_reg <= exitcond_flatten_reg_1477;
        nm_t_mid2_reg_1486_pp0_iter1_reg <= nm_t_mid2_reg_1486;
        tmp_162_reg_1504_pp0_iter1_reg <= tmp_162_reg_1504;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_317_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        nm_t_mid2_reg_1486 <= nm_t_mid2_fu_417_p3;
        tmp_142_reg_1499 <= tmp_142_fu_437_p2;
        tmp_162_reg_1504 <= tmp_162_fu_443_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        nm_t_mid2_reg_1486_pp0_iter2_reg <= nm_t_mid2_reg_1486_pp0_iter1_reg;
        tmp_162_reg_1504_pp0_iter2_reg <= tmp_162_reg_1504_pp0_iter1_reg;
        tmp_162_reg_1504_pp0_iter3_reg <= tmp_162_reg_1504_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_162_reg_1504_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_21_1_reg_1603 <= p_Val2_21_1_fu_1156_p2;
        p_Val2_21_2_reg_1608 <= p_Val2_21_2_fu_1295_p2;
        p_Val2_21_3_reg_1613 <= p_Val2_21_3_fu_1434_p2;
        p_Val2_s_reg_1598 <= p_Val2_s_fu_1017_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_1477_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_100_reg_1553 <= {{p_Val2_1_fu_554_p2[13:7]}};
        tmp_1023_reg_1543 <= p_Val2_s_191_fu_484_p2[32'd6];
        tmp_1026_reg_1558 <= p_Val2_1_fu_554_p2[32'd6];
        tmp_1029_reg_1573 <= p_Val2_2_fu_624_p2[32'd6];
        tmp_1032_reg_1588 <= p_Val2_3_fu_694_p2[32'd6];
        tmp_103_reg_1568 <= {{p_Val2_2_fu_624_p2[13:7]}};
        tmp_106_reg_1583 <= {{p_Val2_3_fu_694_p2[13:7]}};
        tmp_163_reg_1548 <= tmp_163_fu_544_p2;
        tmp_255_1_reg_1563 <= tmp_255_1_fu_614_p2;
        tmp_255_2_reg_1578 <= tmp_255_2_fu_684_p2;
        tmp_255_3_reg_1593 <= tmp_255_3_fu_754_p2;
        tmp_97_reg_1538 <= {{p_Val2_s_191_fu_484_p2[13:7]}};
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_317_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten_reg_1477_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        in_V_V_blk_n = in_V_V_empty_n;
    end else begin
        in_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_flatten_reg_1477_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_V_V_read = 1'b1;
    end else begin
        in_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_162_reg_1504_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        out_V_V_blk_n = out_V_V_full_n;
    end else begin
        out_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((tmp_162_reg_1504_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        out_V_V_write = 1'b1;
    end else begin
        out_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights19_m_weights_1_ce0 = 1'b1;
    end else begin
        weights19_m_weights_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights19_m_weights_2_ce0 = 1'b1;
    end else begin
        weights19_m_weights_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights19_m_weights_3_ce0 = 1'b1;
    end else begin
        weights19_m_weights_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        weights19_m_weights_s_ce0 = 1'b1;
    end else begin
        weights19_m_weights_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond_flatten_fu_317_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((exitcond_flatten_fu_317_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((tmp_162_reg_1504_pp0_iter3_reg == 1'd1) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((exitcond_flatten_reg_1477_pp0_iter1_reg == 1'd0) & (in_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((tmp_162_reg_1504_pp0_iter3_reg == 1'd1) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((exitcond_flatten_reg_1477_pp0_iter1_reg == 1'd0) & (in_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((tmp_162_reg_1504_pp0_iter3_reg == 1'd1) & (out_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((exitcond_flatten_reg_1477_pp0_iter1_reg == 1'd0) & (in_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter2 = ((exitcond_flatten_reg_1477_pp0_iter1_reg == 1'd0) & (in_V_V_empty_n == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter4 = ((tmp_162_reg_1504_pp0_iter3_reg == 1'd1) & (out_V_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign exitcond_flatten4_fu_329_p2 = ((indvar_flatten_reg_252 == 16'd16384) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_317_p2 = ((indvar_flatten4_reg_241 == 21'd1048576) ? 1'b1 : 1'b0);

assign indvar_flatten_next1_fu_323_p2 = (21'd1 + indvar_flatten4_reg_241);

assign indvar_flatten_next_fu_461_p3 = ((exitcond_flatten4_fu_329_p2[0:0] === 1'b1) ? 16'd1 : indvar_flatten_op_fu_455_p2);

assign indvar_flatten_op_fu_455_p2 = (indvar_flatten_reg_252 + 16'd1);

assign macRegisters_0_V_fu_789_p2 = ($signed(tmp_98_fu_772_p1) + $signed(tmp1_fu_783_p2));

assign macRegisters_1_V_fu_812_p2 = ($signed(tmp_101_fu_795_p1) + $signed(tmp2_fu_806_p2));

assign macRegisters_2_V_fu_835_p2 = ($signed(tmp_104_fu_818_p1) + $signed(tmp3_fu_829_p2));

assign macRegisters_3_V_fu_858_p2 = ($signed(tmp_107_fu_841_p1) + $signed(tmp4_fu_852_p2));

assign nm_1_fu_377_p2 = (7'd1 + nm_mid_fu_335_p3);

assign nm_mid2_fu_425_p3 = ((tmp_141_mid_fu_371_p2[0:0] === 1'b1) ? nm_1_fu_377_p2 : nm_mid_fu_335_p3);

assign nm_mid_fu_335_p3 = ((exitcond_flatten4_fu_329_p2[0:0] === 1'b1) ? 7'd0 : nm_reg_263);

assign nm_t_mid2_fu_417_p3 = ((tmp_141_mid_fu_371_p2[0:0] === 1'b1) ? tmp_1021_fu_397_p1 : nm_t_mid_fu_351_p3);

assign nm_t_mid_fu_351_p3 = ((exitcond_flatten4_fu_329_p2[0:0] === 1'b1) ? 6'd0 : tmp_fu_305_p1);

assign not_exitcond_flatten_fu_359_p2 = (exitcond_flatten4_fu_329_p2 ^ 1'd1);

assign out_V_V_din = {{{{p_Val2_21_3_reg_1613}, {p_Val2_21_2_reg_1608}}, {p_Val2_21_1_reg_1603}}, {p_Val2_s_reg_1598}};

assign p_08_cast_cast_fu_476_p1 = $signed(in_V_V_dout);

assign p_Val2_1_fu_554_p0 = weights19_m_weights_2_q0;

assign p_Val2_1_fu_554_p1 = p_08_cast_cast_fu_476_p1;

assign p_Val2_1_fu_554_p2 = ($signed(p_Val2_1_fu_554_p0) * $signed(p_Val2_1_fu_554_p1));

assign p_Val2_21_1_fu_1156_p2 = (macRegisters_1_V_fu_812_p2 + tmp_109_fu_1023_p66);

assign p_Val2_21_2_fu_1295_p2 = (macRegisters_2_V_fu_835_p2 + tmp_110_fu_1162_p66);

assign p_Val2_21_3_fu_1434_p2 = (macRegisters_3_V_fu_858_p2 + tmp_111_fu_1301_p66);

assign p_Val2_2_fu_624_p0 = weights19_m_weights_1_q0;

assign p_Val2_2_fu_624_p1 = p_08_cast_cast_fu_476_p1;

assign p_Val2_2_fu_624_p2 = ($signed(p_Val2_2_fu_624_p0) * $signed(p_Val2_2_fu_624_p1));

assign p_Val2_3_fu_694_p0 = weights19_m_weights_s_q0;

assign p_Val2_3_fu_694_p1 = p_08_cast_cast_fu_476_p1;

assign p_Val2_3_fu_694_p2 = ($signed(p_Val2_3_fu_694_p0) * $signed(p_Val2_3_fu_694_p1));

assign p_Val2_s_191_fu_484_p0 = weights19_m_weights_3_q0;

assign p_Val2_s_191_fu_484_p1 = p_08_cast_cast_fu_476_p1;

assign p_Val2_s_191_fu_484_p2 = ($signed(p_Val2_s_191_fu_484_p0) * $signed(p_Val2_s_191_fu_484_p1));

assign p_Val2_s_fu_1017_p2 = (macRegisters_0_V_fu_789_p2 + tmp_108_fu_884_p66);

assign qb_assign_1_1_fu_798_p2 = (tmp_255_1_reg_1563 & tmp_1026_reg_1558);

assign qb_assign_1_2_fu_821_p2 = (tmp_255_2_reg_1578 & tmp_1029_reg_1573);

assign qb_assign_1_3_fu_844_p2 = (tmp_255_3_reg_1593 & tmp_1032_reg_1588);

assign qb_assign_1_fu_775_p2 = (tmp_163_reg_1548 & tmp_1023_reg_1543);

assign sf_1_fu_449_p2 = (sf_mid2_fu_389_p3 + 9'd1);

assign sf_cast1_fu_433_p1 = sf_mid2_fu_389_p3;

assign sf_mid2_fu_389_p3 = ((tmp_867_fu_383_p2[0:0] === 1'b1) ? 9'd0 : sf_reg_274);

assign start_out = real_start;

assign tmp1_fu_783_p2 = (tmp_164_fu_779_p1 + macRegisters_0_V_9_fu_160);

assign tmp2_fu_806_p2 = (tmp_256_1_fu_802_p1 + macRegisters_1_V_9_fu_164);

assign tmp3_fu_829_p2 = (tmp_256_2_fu_825_p1 + macRegisters_2_V_9_fu_168);

assign tmp4_fu_852_p2 = (tmp_256_3_fu_848_p1 + macRegisters_3_V_9_fu_172);

assign tmp_101_fu_795_p1 = $signed(tmp_100_reg_1553);

assign tmp_1021_fu_397_p1 = nm_1_fu_377_p2[5:0];

assign tmp_1022_fu_490_p3 = p_Val2_s_191_fu_484_p2[32'd13];

assign tmp_1024_fu_516_p1 = p_Val2_s_191_fu_484_p2[0:0];

assign tmp_1025_fu_560_p3 = p_Val2_1_fu_554_p2[32'd13];

assign tmp_1027_fu_586_p1 = p_Val2_1_fu_554_p2[0:0];

assign tmp_1028_fu_630_p3 = p_Val2_2_fu_624_p2[32'd13];

assign tmp_1030_fu_656_p1 = p_Val2_2_fu_624_p2[0:0];

assign tmp_1031_fu_700_p3 = p_Val2_3_fu_694_p2[32'd13];

assign tmp_1033_fu_726_p1 = p_Val2_3_fu_694_p2[0:0];

assign tmp_104_fu_818_p1 = $signed(tmp_103_reg_1568);

assign tmp_107_fu_841_p1 = $signed(tmp_106_reg_1583);

assign tmp_140_fu_309_p3 = {{tmp_fu_305_p1}, {8'd0}};

assign tmp_140_mid1_fu_401_p3 = {{tmp_1021_fu_397_p1}, {8'd0}};

assign tmp_140_mid2_fu_409_p3 = ((tmp_141_mid_fu_371_p2[0:0] === 1'b1) ? tmp_140_mid1_fu_401_p3 : tmp_140_mid_fu_343_p3);

assign tmp_140_mid_fu_343_p3 = ((exitcond_flatten4_fu_329_p2[0:0] === 1'b1) ? 14'd0 : tmp_140_fu_309_p3);

assign tmp_141_mid_fu_371_p2 = (tmp_s_fu_365_p2 & not_exitcond_flatten_fu_359_p2);

assign tmp_142_fu_437_p2 = (sf_cast1_fu_433_p1 + tmp_140_mid2_fu_409_p3);

assign tmp_145_fu_469_p1 = tmp_142_reg_1499;

assign tmp_147_fu_520_p2 = (tmp_1024_fu_516_p1 | tmp_1022_fu_490_p3);

assign tmp_148_fu_526_p4 = {{p_Val2_s_191_fu_484_p2[5:1]}};

assign tmp_149_fu_536_p3 = {{tmp_148_fu_526_p4}, {tmp_147_fu_520_p2}};

assign tmp_151_fu_590_p2 = (tmp_1027_fu_586_p1 | tmp_1025_fu_560_p3);

assign tmp_152_fu_596_p4 = {{p_Val2_1_fu_554_p2[5:1]}};

assign tmp_153_fu_606_p3 = {{tmp_152_fu_596_p4}, {tmp_151_fu_590_p2}};

assign tmp_155_fu_660_p2 = (tmp_1030_fu_656_p1 | tmp_1028_fu_630_p3);

assign tmp_156_fu_666_p4 = {{p_Val2_2_fu_624_p2[5:1]}};

assign tmp_157_fu_676_p3 = {{tmp_156_fu_666_p4}, {tmp_155_fu_660_p2}};

assign tmp_159_fu_730_p2 = (tmp_1033_fu_726_p1 | tmp_1031_fu_700_p3);

assign tmp_160_fu_736_p4 = {{p_Val2_3_fu_694_p2[5:1]}};

assign tmp_161_fu_746_p3 = {{tmp_160_fu_736_p4}, {tmp_159_fu_730_p2}};

assign tmp_162_fu_443_p2 = ((sf_mid2_fu_389_p3 == 9'd255) ? 1'b1 : 1'b0);

assign tmp_163_fu_544_p2 = ((tmp_149_fu_536_p3 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_164_fu_779_p1 = qb_assign_1_fu_775_p2;

assign tmp_255_1_fu_614_p2 = ((tmp_153_fu_606_p3 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_255_2_fu_684_p2 = ((tmp_157_fu_676_p3 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_255_3_fu_754_p2 = ((tmp_161_fu_746_p3 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_256_1_fu_802_p1 = qb_assign_1_1_fu_798_p2;

assign tmp_256_2_fu_825_p1 = qb_assign_1_2_fu_821_p2;

assign tmp_256_3_fu_848_p1 = qb_assign_1_3_fu_844_p2;

assign tmp_867_fu_383_p2 = (tmp_141_mid_fu_371_p2 | exitcond_flatten4_fu_329_p2);

assign tmp_98_fu_772_p1 = $signed(tmp_97_reg_1538);

assign tmp_fu_305_p1 = nm_reg_263[5:0];

assign tmp_s_fu_365_p2 = ((sf_reg_274 == 9'd256) ? 1'b1 : 1'b0);

assign weights19_m_weights_1_address0 = tmp_145_fu_469_p1;

assign weights19_m_weights_2_address0 = tmp_145_fu_469_p1;

assign weights19_m_weights_3_address0 = tmp_145_fu_469_p1;

assign weights19_m_weights_s_address0 = tmp_145_fu_469_p1;

endmodule //Conv1DMac_new
