-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity loadPCL_pcl_V_10438_rom is 
    generic(
             DWIDTH     : integer := 8; 
             AWIDTH     : integer := 7; 
             MEM_SIZE    : integer := 96
    ); 
    port (
          addr0      : in std_logic_vector(AWIDTH-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(DWIDTH-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of loadPCL_pcl_V_10438_rom is 

signal addr0_tmp : std_logic_vector(AWIDTH-1 downto 0); 
type mem_array is array (0 to MEM_SIZE-1) of std_logic_vector (DWIDTH-1 downto 0); 
signal mem : mem_array := (
    0 => "11110111", 1 => "11010101", 2 => "11110010", 3 => "00010111", 
    4 => "10110110", 5 => "11110010", 6 => "11101100", 7 => "11100110", 
    8 => "00100011", 9 => "00000111", 10 => "01000000", 11 => "00011011", 
    12 => "00011010", 13 => "01111010", 14 => "00100011", 15 => "00010011", 
    16 => "00000011", 17 => "00010111", 18 => "11110011", 19 => "11001100", 
    20 => "00000111", 21 => "11110010", 22 => "00110101", 23 => "00100000", 
    24 => "00100010", 25 => "11001000", 26 => "00000110", 27 => "11101010", 
    28 => "11100101", 29 => "00001010", 30 => "00000001", 31 => "11001010", 
    32 to 33=> "00101010", 34 => "00101001", 35 => "00101011", 36 => "11111010", 
    37 => "11110001", 38 => "00000100", 39 => "00101101", 40 => "11110100", 
    41 => "00110001", 42 => "00100110", 43 => "11101010", 44 => "11111101", 
    45 => "00100101", 46 => "11010000", 47 => "11101111", 48 => "00001000", 
    49 => "11101011", 50 => "00110111", 51 => "00100100", 52 => "11111011", 
    53 => "00100011", 54 => "11111001", 55 => "01001101", 56 => "00101011", 
    57 => "00010000", 58 => "01111000", 59 => "00100100", 60 => "00110101", 
    61 => "00011100", 62 => "00110000", 63 => "00101000", 64 => "11011111", 
    65 => "00110110", 66 => "00101000", 67 => "10110000", 68 => "11110000", 
    69 => "00001100", 70 => "00111100", 71 => "00010111", 72 => "00101000", 
    73 => "00111001", 74 => "00011011", 75 => "11110110", 76 => "00001100", 
    77 => "00010000", 78 => "00100010", 79 => "10111111", 80 => "11111100", 
    81 => "00000111", 82 => "10100100", 83 => "11010011", 84 => "00111111", 
    85 => "00001110", 86 => "00100100", 87 => "00101100", 88 => "11001010", 
    89 => "00000010", 90 => "00100000", 91 => "01110100", 92 => "00011111", 
    93 => "00010100", 94 => "00110010", 95 => "00110111" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity loadPCL_pcl_V_10438 is
    generic (
        DataWidth : INTEGER := 8;
        AddressRange : INTEGER := 96;
        AddressWidth : INTEGER := 7);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of loadPCL_pcl_V_10438 is
    component loadPCL_pcl_V_10438_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    loadPCL_pcl_V_10438_rom_U :  component loadPCL_pcl_V_10438_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


