# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/efree/Desktop/FC1_lastLayerOnly/FC1/solution1/impl/ip/constraints/FCL1_ooc.xdc

# Block Designs: bd/pmlp/pmlp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp || ORIG_REF_NAME==pmlp} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_processing_system7_0_0/pmlp_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_processing_system7_0_0 || ORIG_REF_NAME==pmlp_processing_system7_0_0} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_computeS4_3_0_2/pmlp_computeS4_3_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_computeS4_3_0_2 || ORIG_REF_NAME==pmlp_computeS4_3_0_2} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_computeS4_2_0_2/pmlp_computeS4_2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_computeS4_2_0_2 || ORIG_REF_NAME==pmlp_computeS4_2_0_2} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_computeS4_1_0_2/pmlp_computeS4_1_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_computeS4_1_0_2 || ORIG_REF_NAME==pmlp_computeS4_1_0_2} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_computeS3_0_2/pmlp_computeS3_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_computeS3_0_2 || ORIG_REF_NAME==pmlp_computeS3_0_2} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_computeS2_0_2/pmlp_computeS2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_computeS2_0_2 || ORIG_REF_NAME==pmlp_computeS2_0_2} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_computeS1_0_2/pmlp_computeS1_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_computeS1_0_2 || ORIG_REF_NAME==pmlp_computeS1_0_2} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_FCL1_0_1/pmlp_FCL1_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_FCL1_0_1 || ORIG_REF_NAME==pmlp_FCL1_0_1} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_axi_dma_0_0/pmlp_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_axi_dma_0_0 || ORIG_REF_NAME==pmlp_axi_dma_0_0} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_xbar_0/pmlp_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_xbar_0 || ORIG_REF_NAME==pmlp_xbar_0} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_auto_pc_0/pmlp_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_auto_pc_0 || ORIG_REF_NAME==pmlp_auto_pc_0} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_ps7_0_axi_periph_0/pmlp_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_ps7_0_axi_periph_0 || ORIG_REF_NAME==pmlp_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_rst_ps7_0_50M_0/pmlp_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_rst_ps7_0_50M_0 || ORIG_REF_NAME==pmlp_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_xlconcat_0_0/pmlp_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_xlconcat_0_0 || ORIG_REF_NAME==pmlp_xlconcat_0_0} -quiet] -quiet

# IP: bd/pmlp/ip/pmlp_axi_smc_0/pmlp_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pmlp_axi_smc_0 || ORIG_REF_NAME==pmlp_axi_smc_0} -quiet] -quiet

# XDC: bd/pmlp/pmlp_ooc.xdc
