// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Conv1DMac_new_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Conv1DMac_new_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Conv1DMac_new_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> Conv1DMac_new_1::ap_ST_fsm_state1 = "1";
const sc_lv<3> Conv1DMac_new_1::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> Conv1DMac_new_1::ap_ST_fsm_state7 = "100";
const bool Conv1DMac_new_1::ap_const_boolean_1 = true;
const sc_lv<32> Conv1DMac_new_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool Conv1DMac_new_1::ap_const_boolean_0 = false;
const sc_lv<1> Conv1DMac_new_1::ap_const_lv1_0 = "0";
const sc_lv<1> Conv1DMac_new_1::ap_const_lv1_1 = "1";
const sc_lv<32> Conv1DMac_new_1::ap_const_lv32_1 = "1";
const sc_lv<20> Conv1DMac_new_1::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<14> Conv1DMac_new_1::ap_const_lv14_0 = "00000000000000";
const sc_lv<6> Conv1DMac_new_1::ap_const_lv6_0 = "000000";
const sc_lv<8> Conv1DMac_new_1::ap_const_lv8_0 = "00000000";
const sc_lv<7> Conv1DMac_new_1::ap_const_lv7_0 = "0000000";
const sc_lv<20> Conv1DMac_new_1::ap_const_lv20_80000 = "10000000000000000000";
const sc_lv<20> Conv1DMac_new_1::ap_const_lv20_1 = "1";
const sc_lv<14> Conv1DMac_new_1::ap_const_lv14_1000 = "1000000000000";
const sc_lv<12> Conv1DMac_new_1::ap_const_lv12_0 = "000000000000";
const sc_lv<5> Conv1DMac_new_1::ap_const_lv5_0 = "00000";
const sc_lv<8> Conv1DMac_new_1::ap_const_lv8_80 = "10000000";
const sc_lv<6> Conv1DMac_new_1::ap_const_lv6_1 = "1";
const sc_lv<8> Conv1DMac_new_1::ap_const_lv8_7F = "1111111";
const sc_lv<8> Conv1DMac_new_1::ap_const_lv8_1 = "1";
const sc_lv<14> Conv1DMac_new_1::ap_const_lv14_1 = "1";
const sc_lv<32> Conv1DMac_new_1::ap_const_lv32_E = "1110";
const sc_lv<32> Conv1DMac_new_1::ap_const_lv32_7 = "111";
const sc_lv<32> Conv1DMac_new_1::ap_const_lv32_6 = "110";
const sc_lv<32> Conv1DMac_new_1::ap_const_lv32_5 = "101";
const sc_lv<8> Conv1DMac_new_1::ap_const_lv8_FF = "11111111";
const sc_lv<32> Conv1DMac_new_1::ap_const_lv32_2 = "10";

Conv1DMac_new_1::Conv1DMac_new_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    weights10_m_weights_3_U = new Conv1DMac_new_1_wQgW("weights10_m_weights_3_U");
    weights10_m_weights_3_U->clk(ap_clk);
    weights10_m_weights_3_U->reset(ap_rst);
    weights10_m_weights_3_U->address0(weights10_m_weights_3_address0);
    weights10_m_weights_3_U->ce0(weights10_m_weights_3_ce0);
    weights10_m_weights_3_U->q0(weights10_m_weights_3_q0);
    weights10_m_weights_2_U = new Conv1DMac_new_1_wRg6("weights10_m_weights_2_U");
    weights10_m_weights_2_U->clk(ap_clk);
    weights10_m_weights_2_U->reset(ap_rst);
    weights10_m_weights_2_U->address0(weights10_m_weights_2_address0);
    weights10_m_weights_2_U->ce0(weights10_m_weights_2_ce0);
    weights10_m_weights_2_U->q0(weights10_m_weights_2_q0);
    weights10_m_weights_1_U = new Conv1DMac_new_1_wShg("weights10_m_weights_1_U");
    weights10_m_weights_1_U->clk(ap_clk);
    weights10_m_weights_1_U->reset(ap_rst);
    weights10_m_weights_1_U->address0(weights10_m_weights_1_address0);
    weights10_m_weights_1_U->ce0(weights10_m_weights_1_ce0);
    weights10_m_weights_1_U->q0(weights10_m_weights_1_q0);
    weights10_m_weights_s_U = new Conv1DMac_new_1_wThq("weights10_m_weights_s_U");
    weights10_m_weights_s_U->clk(ap_clk);
    weights10_m_weights_s_U->reset(ap_rst);
    weights10_m_weights_s_U->address0(weights10_m_weights_s_address0);
    weights10_m_weights_s_U->ce0(weights10_m_weights_s_ce0);
    weights10_m_weights_s_U->q0(weights10_m_weights_s_q0);
    computeS2_mux_325yd2_x_x_x_x_U125 = new computeS2_mux_325yd2_x_x_x_x<1,1,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,5,8>("computeS2_mux_325yd2_x_x_x_x_U125");
    computeS2_mux_325yd2_x_x_x_x_U125->din0(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din1(ap_var_for_const1);
    computeS2_mux_325yd2_x_x_x_x_U125->din2(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din3(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din4(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din5(ap_var_for_const2);
    computeS2_mux_325yd2_x_x_x_x_U125->din6(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din7(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din8(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din9(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din10(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din11(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din12(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din13(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din14(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din15(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din16(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din17(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din18(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din19(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din20(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din21(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din22(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din23(ap_var_for_const1);
    computeS2_mux_325yd2_x_x_x_x_U125->din24(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din25(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din26(ap_var_for_const1);
    computeS2_mux_325yd2_x_x_x_x_U125->din27(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din28(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din29(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din30(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din31(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U125->din32(nm_t_mid2_reg_1158_pp0_iter2_reg);
    computeS2_mux_325yd2_x_x_x_x_U125->dout(tmp_123_fu_812_p34);
    computeS2_mux_325yd2_x_x_x_x_U126 = new computeS2_mux_325yd2_x_x_x_x<1,1,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,5,8>("computeS2_mux_325yd2_x_x_x_x_U126");
    computeS2_mux_325yd2_x_x_x_x_U126->din0(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din1(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din2(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din3(ap_var_for_const1);
    computeS2_mux_325yd2_x_x_x_x_U126->din4(ap_var_for_const2);
    computeS2_mux_325yd2_x_x_x_x_U126->din5(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din6(ap_var_for_const1);
    computeS2_mux_325yd2_x_x_x_x_U126->din7(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din8(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din9(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din10(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din11(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din12(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din13(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din14(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din15(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din16(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din17(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din18(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din19(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din20(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din21(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din22(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din23(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din24(ap_var_for_const1);
    computeS2_mux_325yd2_x_x_x_x_U126->din25(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din26(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din27(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din28(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din29(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din30(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din31(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U126->din32(nm_t_mid2_reg_1158_pp0_iter2_reg);
    computeS2_mux_325yd2_x_x_x_x_U126->dout(tmp_124_fu_887_p34);
    computeS2_mux_325yd2_x_x_x_x_U127 = new computeS2_mux_325yd2_x_x_x_x<1,1,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,5,8>("computeS2_mux_325yd2_x_x_x_x_U127");
    computeS2_mux_325yd2_x_x_x_x_U127->din0(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din1(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din2(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din3(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din4(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din5(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din6(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din7(ap_var_for_const1);
    computeS2_mux_325yd2_x_x_x_x_U127->din8(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din9(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din10(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din11(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din12(ap_var_for_const2);
    computeS2_mux_325yd2_x_x_x_x_U127->din13(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din14(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din15(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din16(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din17(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din18(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din19(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din20(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din21(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din22(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din23(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din24(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din25(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din26(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din27(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din28(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din29(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din30(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din31(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U127->din32(nm_t_mid2_reg_1158_pp0_iter2_reg);
    computeS2_mux_325yd2_x_x_x_x_U127->dout(tmp_125_fu_962_p34);
    computeS2_mux_325yd2_x_x_x_x_U128 = new computeS2_mux_325yd2_x_x_x_x<1,1,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,5,8>("computeS2_mux_325yd2_x_x_x_x_U128");
    computeS2_mux_325yd2_x_x_x_x_U128->din0(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din1(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din2(ap_var_for_const1);
    computeS2_mux_325yd2_x_x_x_x_U128->din3(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din4(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din5(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din6(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din7(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din8(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din9(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din10(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din11(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din12(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din13(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din14(ap_var_for_const2);
    computeS2_mux_325yd2_x_x_x_x_U128->din15(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din16(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din17(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din18(ap_var_for_const2);
    computeS2_mux_325yd2_x_x_x_x_U128->din19(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din20(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din21(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din22(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din23(ap_var_for_const2);
    computeS2_mux_325yd2_x_x_x_x_U128->din24(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din25(ap_var_for_const2);
    computeS2_mux_325yd2_x_x_x_x_U128->din26(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din27(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din28(ap_var_for_const2);
    computeS2_mux_325yd2_x_x_x_x_U128->din29(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din30(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din31(ap_var_for_const0);
    computeS2_mux_325yd2_x_x_x_x_U128->din32(nm_t_mid2_reg_1158_pp0_iter2_reg);
    computeS2_mux_325yd2_x_x_x_x_U128->dout(tmp_126_fu_1037_p34);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exitcond_flatten6_reg_1149_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_100_reg_1176_pp0_iter3_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exitcond_flatten6_reg_1149_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_100_reg_1176_pp0_iter3_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exitcond_flatten6_reg_1149_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_100_reg_1176_pp0_iter3_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( exitcond_flatten6_reg_1149_pp0_iter1_reg );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);
    sensitive << ( out_V_V_full_n );
    sensitive << ( tmp_100_reg_1176_pp0_iter3_reg );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond_flatten6_fu_261_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_exitcond_flatten6_fu_261_p2);
    sensitive << ( indvar_flatten6_reg_185 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_flatten_fu_273_p2);
    sensitive << ( indvar_flatten_reg_196 );
    sensitive << ( exitcond_flatten6_fu_261_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_in_V_V_blk_n);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( exitcond_flatten6_reg_1149_pp0_iter1_reg );

    SC_METHOD(thread_in_V_V_read);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exitcond_flatten6_reg_1149_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_indvar_flatten_next6_fu_267_p2);
    sensitive << ( indvar_flatten6_reg_185 );

    SC_METHOD(thread_indvar_flatten_next_fu_405_p3);
    sensitive << ( exitcond_flatten_fu_273_p2 );
    sensitive << ( indvar_flatten_op_fu_399_p2 );

    SC_METHOD(thread_indvar_flatten_op_fu_399_p2);
    sensitive << ( indvar_flatten_reg_196 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_macRegisters_0_V_fu_730_p2);
    sensitive << ( tmp_101_reg_1210 );
    sensitive << ( tmp1_fu_724_p2 );

    SC_METHOD(thread_macRegisters_1_V_fu_749_p2);
    sensitive << ( tmp_108_reg_1225 );
    sensitive << ( tmp2_fu_743_p2 );

    SC_METHOD(thread_macRegisters_2_V_fu_768_p2);
    sensitive << ( tmp_113_reg_1240 );
    sensitive << ( tmp3_fu_762_p2 );

    SC_METHOD(thread_macRegisters_3_V_fu_787_p2);
    sensitive << ( tmp_118_reg_1255 );
    sensitive << ( tmp4_fu_781_p2 );

    SC_METHOD(thread_nm_2_fu_321_p2);
    sensitive << ( nm_mid_fu_279_p3 );

    SC_METHOD(thread_nm_mid2_fu_369_p3);
    sensitive << ( nm_mid_fu_279_p3 );
    sensitive << ( tmp_97_mid_fu_315_p2 );
    sensitive << ( nm_2_fu_321_p2 );

    SC_METHOD(thread_nm_mid_fu_279_p3);
    sensitive << ( nm_reg_207 );
    sensitive << ( exitcond_flatten_fu_273_p2 );

    SC_METHOD(thread_nm_t_mid2_fu_361_p3);
    sensitive << ( tmp_97_mid_fu_315_p2 );
    sensitive << ( tmp_351_fu_341_p1 );
    sensitive << ( nm_t_mid_fu_295_p3 );

    SC_METHOD(thread_nm_t_mid_fu_295_p3);
    sensitive << ( tmp_fu_249_p1 );
    sensitive << ( exitcond_flatten_fu_273_p2 );

    SC_METHOD(thread_not_exitcond_flatten_fu_303_p2);
    sensitive << ( exitcond_flatten_fu_273_p2 );

    SC_METHOD(thread_out_V_V_blk_n);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_100_reg_1176_pp0_iter3_reg );

    SC_METHOD(thread_out_V_V_din);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_100_reg_1176_pp0_iter3_reg );
    sensitive << ( p_Val2_s_reg_1270 );
    sensitive << ( p_Val2_22_1_reg_1275 );
    sensitive << ( p_Val2_22_2_reg_1280 );
    sensitive << ( p_Val2_22_3_reg_1285 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_out_V_V_write);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_100_reg_1176_pp0_iter3_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_08_cast_fu_420_p1);
    sensitive << ( in_V_V_dout );

    SC_METHOD(thread_p_Val2_1_fu_498_p0);
    sensitive << ( weights10_m_weights_2_q0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_p_Val2_1_fu_498_p1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( p_08_cast_fu_420_p1 );

    SC_METHOD(thread_p_Val2_1_fu_498_p2);
    sensitive << ( p_Val2_1_fu_498_p0 );
    sensitive << ( p_Val2_1_fu_498_p1 );

    SC_METHOD(thread_p_Val2_22_1_fu_956_p2);
    sensitive << ( macRegisters_1_V_fu_749_p2 );
    sensitive << ( tmp_124_fu_887_p34 );

    SC_METHOD(thread_p_Val2_22_2_fu_1031_p2);
    sensitive << ( macRegisters_2_V_fu_768_p2 );
    sensitive << ( tmp_125_fu_962_p34 );

    SC_METHOD(thread_p_Val2_22_3_fu_1106_p2);
    sensitive << ( macRegisters_3_V_fu_787_p2 );
    sensitive << ( tmp_126_fu_1037_p34 );

    SC_METHOD(thread_p_Val2_2_fu_568_p0);
    sensitive << ( weights10_m_weights_1_q0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_p_Val2_2_fu_568_p1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( p_08_cast_fu_420_p1 );

    SC_METHOD(thread_p_Val2_2_fu_568_p2);
    sensitive << ( p_Val2_2_fu_568_p0 );
    sensitive << ( p_Val2_2_fu_568_p1 );

    SC_METHOD(thread_p_Val2_3_fu_638_p0);
    sensitive << ( weights10_m_weights_s_q0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_p_Val2_3_fu_638_p1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( p_08_cast_fu_420_p1 );

    SC_METHOD(thread_p_Val2_3_fu_638_p2);
    sensitive << ( p_Val2_3_fu_638_p0 );
    sensitive << ( p_Val2_3_fu_638_p1 );

    SC_METHOD(thread_p_Val2_s_136_fu_428_p0);
    sensitive << ( weights10_m_weights_3_q0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_p_Val2_s_136_fu_428_p1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( p_08_cast_fu_420_p1 );

    SC_METHOD(thread_p_Val2_s_136_fu_428_p2);
    sensitive << ( p_Val2_s_136_fu_428_p0 );
    sensitive << ( p_Val2_s_136_fu_428_p1 );

    SC_METHOD(thread_p_Val2_s_fu_881_p2);
    sensitive << ( macRegisters_0_V_fu_730_p2 );
    sensitive << ( tmp_123_fu_812_p34 );

    SC_METHOD(thread_qb_assign_2_1_fu_735_p2);
    sensitive << ( tmp_356_reg_1230 );
    sensitive << ( tmp_227_1_reg_1235 );

    SC_METHOD(thread_qb_assign_2_2_fu_754_p2);
    sensitive << ( tmp_359_reg_1245 );
    sensitive << ( tmp_227_2_reg_1250 );

    SC_METHOD(thread_qb_assign_2_3_fu_773_p2);
    sensitive << ( tmp_362_reg_1260 );
    sensitive << ( tmp_227_3_reg_1265 );

    SC_METHOD(thread_qb_assign_2_fu_716_p2);
    sensitive << ( tmp_353_reg_1215 );
    sensitive << ( tmp_106_reg_1220 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_sf_2_fu_393_p2);
    sensitive << ( sf_mid2_fu_333_p3 );

    SC_METHOD(thread_sf_cast1_fu_377_p1);
    sensitive << ( sf_mid2_fu_333_p3 );

    SC_METHOD(thread_sf_mid2_fu_333_p3);
    sensitive << ( sf_reg_218 );
    sensitive << ( tmp_274_fu_327_p2 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp1_fu_724_p2);
    sensitive << ( macRegisters_0_V_4_fu_104 );
    sensitive << ( tmp_107_fu_720_p1 );

    SC_METHOD(thread_tmp2_fu_743_p2);
    sensitive << ( macRegisters_1_V_4_fu_108 );
    sensitive << ( tmp_228_1_fu_739_p1 );

    SC_METHOD(thread_tmp3_fu_762_p2);
    sensitive << ( macRegisters_2_V_4_fu_112 );
    sensitive << ( tmp_228_2_fu_758_p1 );

    SC_METHOD(thread_tmp4_fu_781_p2);
    sensitive << ( macRegisters_3_V_4_fu_116 );
    sensitive << ( tmp_228_3_fu_777_p1 );

    SC_METHOD(thread_tmp_100_fu_387_p2);
    sensitive << ( exitcond_flatten6_fu_261_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( sf_mid2_fu_333_p3 );

    SC_METHOD(thread_tmp_103_fu_464_p2);
    sensitive << ( tmp_354_fu_460_p1 );
    sensitive << ( tmp_352_fu_434_p3 );

    SC_METHOD(thread_tmp_104_fu_470_p4);
    sensitive << ( p_Val2_s_136_fu_428_p2 );

    SC_METHOD(thread_tmp_105_fu_480_p3);
    sensitive << ( tmp_104_fu_470_p4 );
    sensitive << ( tmp_103_fu_464_p2 );

    SC_METHOD(thread_tmp_106_fu_488_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exitcond_flatten6_reg_1149_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_105_fu_480_p3 );

    SC_METHOD(thread_tmp_107_fu_720_p1);
    sensitive << ( qb_assign_2_fu_716_p2 );

    SC_METHOD(thread_tmp_110_fu_534_p2);
    sensitive << ( tmp_357_fu_530_p1 );
    sensitive << ( tmp_355_fu_504_p3 );

    SC_METHOD(thread_tmp_111_fu_540_p4);
    sensitive << ( p_Val2_1_fu_498_p2 );

    SC_METHOD(thread_tmp_112_fu_550_p3);
    sensitive << ( tmp_111_fu_540_p4 );
    sensitive << ( tmp_110_fu_534_p2 );

    SC_METHOD(thread_tmp_115_fu_604_p2);
    sensitive << ( tmp_360_fu_600_p1 );
    sensitive << ( tmp_358_fu_574_p3 );

    SC_METHOD(thread_tmp_116_fu_610_p4);
    sensitive << ( p_Val2_2_fu_568_p2 );

    SC_METHOD(thread_tmp_117_fu_620_p3);
    sensitive << ( tmp_116_fu_610_p4 );
    sensitive << ( tmp_115_fu_604_p2 );

    SC_METHOD(thread_tmp_120_fu_674_p2);
    sensitive << ( tmp_363_fu_670_p1 );
    sensitive << ( tmp_361_fu_644_p3 );

    SC_METHOD(thread_tmp_121_fu_680_p4);
    sensitive << ( p_Val2_3_fu_638_p2 );

    SC_METHOD(thread_tmp_122_fu_690_p3);
    sensitive << ( tmp_121_fu_680_p4 );
    sensitive << ( tmp_120_fu_674_p2 );

    SC_METHOD(thread_tmp_227_1_fu_558_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exitcond_flatten6_reg_1149_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_112_fu_550_p3 );

    SC_METHOD(thread_tmp_227_2_fu_628_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exitcond_flatten6_reg_1149_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_117_fu_620_p3 );

    SC_METHOD(thread_tmp_227_3_fu_698_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( exitcond_flatten6_reg_1149_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_122_fu_690_p3 );

    SC_METHOD(thread_tmp_228_1_fu_739_p1);
    sensitive << ( qb_assign_2_1_fu_735_p2 );

    SC_METHOD(thread_tmp_228_2_fu_758_p1);
    sensitive << ( qb_assign_2_2_fu_754_p2 );

    SC_METHOD(thread_tmp_228_3_fu_777_p1);
    sensitive << ( qb_assign_2_3_fu_773_p2 );

    SC_METHOD(thread_tmp_274_fu_327_p2);
    sensitive << ( exitcond_flatten_fu_273_p2 );
    sensitive << ( tmp_97_mid_fu_315_p2 );

    SC_METHOD(thread_tmp_292_fu_309_p2);
    sensitive << ( sf_reg_218 );
    sensitive << ( exitcond_flatten6_fu_261_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_351_fu_341_p1);
    sensitive << ( nm_2_fu_321_p2 );

    SC_METHOD(thread_tmp_352_fu_434_p3);
    sensitive << ( p_Val2_s_136_fu_428_p2 );

    SC_METHOD(thread_tmp_354_fu_460_p1);
    sensitive << ( p_Val2_s_136_fu_428_p2 );

    SC_METHOD(thread_tmp_355_fu_504_p3);
    sensitive << ( p_Val2_1_fu_498_p2 );

    SC_METHOD(thread_tmp_357_fu_530_p1);
    sensitive << ( p_Val2_1_fu_498_p2 );

    SC_METHOD(thread_tmp_358_fu_574_p3);
    sensitive << ( p_Val2_2_fu_568_p2 );

    SC_METHOD(thread_tmp_360_fu_600_p1);
    sensitive << ( p_Val2_2_fu_568_p2 );

    SC_METHOD(thread_tmp_361_fu_644_p3);
    sensitive << ( p_Val2_3_fu_638_p2 );

    SC_METHOD(thread_tmp_363_fu_670_p1);
    sensitive << ( p_Val2_3_fu_638_p2 );

    SC_METHOD(thread_tmp_96_fu_253_p3);
    sensitive << ( tmp_fu_249_p1 );

    SC_METHOD(thread_tmp_96_mid1_fu_345_p3);
    sensitive << ( tmp_351_fu_341_p1 );

    SC_METHOD(thread_tmp_96_mid2_fu_353_p3);
    sensitive << ( tmp_97_mid_fu_315_p2 );
    sensitive << ( tmp_96_mid1_fu_345_p3 );
    sensitive << ( tmp_96_mid_fu_287_p3 );

    SC_METHOD(thread_tmp_96_mid_fu_287_p3);
    sensitive << ( exitcond_flatten_fu_273_p2 );
    sensitive << ( tmp_96_fu_253_p3 );

    SC_METHOD(thread_tmp_97_mid_fu_315_p2);
    sensitive << ( tmp_292_fu_309_p2 );
    sensitive << ( not_exitcond_flatten_fu_303_p2 );

    SC_METHOD(thread_tmp_98_fu_381_p2);
    sensitive << ( sf_cast1_fu_377_p1 );
    sensitive << ( tmp_96_mid2_fu_353_p3 );

    SC_METHOD(thread_tmp_99_fu_413_p1);
    sensitive << ( tmp_98_reg_1171 );

    SC_METHOD(thread_tmp_fu_249_p1);
    sensitive << ( nm_reg_207 );

    SC_METHOD(thread_weights10_m_weights_1_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_99_fu_413_p1 );

    SC_METHOD(thread_weights10_m_weights_1_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_weights10_m_weights_2_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_99_fu_413_p1 );

    SC_METHOD(thread_weights10_m_weights_2_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_weights10_m_weights_3_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_99_fu_413_p1 );

    SC_METHOD(thread_weights10_m_weights_3_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_weights10_m_weights_s_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_99_fu_413_p1 );

    SC_METHOD(thread_weights10_m_weights_s_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( exitcond_flatten6_fu_261_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Conv1DMac_new_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, in_V_V_dout, "(port)in_V_V_dout");
    sc_trace(mVcdFile, in_V_V_empty_n, "(port)in_V_V_empty_n");
    sc_trace(mVcdFile, in_V_V_read, "(port)in_V_V_read");
    sc_trace(mVcdFile, out_V_V_din, "(port)out_V_V_din");
    sc_trace(mVcdFile, out_V_V_full_n, "(port)out_V_V_full_n");
    sc_trace(mVcdFile, out_V_V_write, "(port)out_V_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, weights10_m_weights_3_address0, "weights10_m_weights_3_address0");
    sc_trace(mVcdFile, weights10_m_weights_3_ce0, "weights10_m_weights_3_ce0");
    sc_trace(mVcdFile, weights10_m_weights_3_q0, "weights10_m_weights_3_q0");
    sc_trace(mVcdFile, weights10_m_weights_2_address0, "weights10_m_weights_2_address0");
    sc_trace(mVcdFile, weights10_m_weights_2_ce0, "weights10_m_weights_2_ce0");
    sc_trace(mVcdFile, weights10_m_weights_2_q0, "weights10_m_weights_2_q0");
    sc_trace(mVcdFile, weights10_m_weights_1_address0, "weights10_m_weights_1_address0");
    sc_trace(mVcdFile, weights10_m_weights_1_ce0, "weights10_m_weights_1_ce0");
    sc_trace(mVcdFile, weights10_m_weights_1_q0, "weights10_m_weights_1_q0");
    sc_trace(mVcdFile, weights10_m_weights_s_address0, "weights10_m_weights_s_address0");
    sc_trace(mVcdFile, weights10_m_weights_s_ce0, "weights10_m_weights_s_ce0");
    sc_trace(mVcdFile, weights10_m_weights_s_q0, "weights10_m_weights_s_q0");
    sc_trace(mVcdFile, in_V_V_blk_n, "in_V_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, exitcond_flatten6_reg_1149, "exitcond_flatten6_reg_1149");
    sc_trace(mVcdFile, exitcond_flatten6_reg_1149_pp0_iter1_reg, "exitcond_flatten6_reg_1149_pp0_iter1_reg");
    sc_trace(mVcdFile, out_V_V_blk_n, "out_V_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, tmp_100_reg_1176, "tmp_100_reg_1176");
    sc_trace(mVcdFile, tmp_100_reg_1176_pp0_iter3_reg, "tmp_100_reg_1176_pp0_iter3_reg");
    sc_trace(mVcdFile, indvar_flatten6_reg_185, "indvar_flatten6_reg_185");
    sc_trace(mVcdFile, indvar_flatten_reg_196, "indvar_flatten_reg_196");
    sc_trace(mVcdFile, nm_reg_207, "nm_reg_207");
    sc_trace(mVcdFile, sf_reg_218, "sf_reg_218");
    sc_trace(mVcdFile, exitcond_flatten6_fu_261_p2, "exitcond_flatten6_fu_261_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, indvar_flatten_next6_fu_267_p2, "indvar_flatten_next6_fu_267_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, nm_t_mid2_fu_361_p3, "nm_t_mid2_fu_361_p3");
    sc_trace(mVcdFile, nm_t_mid2_reg_1158, "nm_t_mid2_reg_1158");
    sc_trace(mVcdFile, nm_t_mid2_reg_1158_pp0_iter1_reg, "nm_t_mid2_reg_1158_pp0_iter1_reg");
    sc_trace(mVcdFile, nm_t_mid2_reg_1158_pp0_iter2_reg, "nm_t_mid2_reg_1158_pp0_iter2_reg");
    sc_trace(mVcdFile, nm_mid2_fu_369_p3, "nm_mid2_fu_369_p3");
    sc_trace(mVcdFile, tmp_98_fu_381_p2, "tmp_98_fu_381_p2");
    sc_trace(mVcdFile, tmp_98_reg_1171, "tmp_98_reg_1171");
    sc_trace(mVcdFile, tmp_100_fu_387_p2, "tmp_100_fu_387_p2");
    sc_trace(mVcdFile, tmp_100_reg_1176_pp0_iter1_reg, "tmp_100_reg_1176_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_100_reg_1176_pp0_iter2_reg, "tmp_100_reg_1176_pp0_iter2_reg");
    sc_trace(mVcdFile, sf_2_fu_393_p2, "sf_2_fu_393_p2");
    sc_trace(mVcdFile, indvar_flatten_next_fu_405_p3, "indvar_flatten_next_fu_405_p3");
    sc_trace(mVcdFile, tmp_101_reg_1210, "tmp_101_reg_1210");
    sc_trace(mVcdFile, tmp_353_reg_1215, "tmp_353_reg_1215");
    sc_trace(mVcdFile, tmp_106_fu_488_p2, "tmp_106_fu_488_p2");
    sc_trace(mVcdFile, tmp_106_reg_1220, "tmp_106_reg_1220");
    sc_trace(mVcdFile, tmp_108_reg_1225, "tmp_108_reg_1225");
    sc_trace(mVcdFile, tmp_356_reg_1230, "tmp_356_reg_1230");
    sc_trace(mVcdFile, tmp_227_1_fu_558_p2, "tmp_227_1_fu_558_p2");
    sc_trace(mVcdFile, tmp_227_1_reg_1235, "tmp_227_1_reg_1235");
    sc_trace(mVcdFile, tmp_113_reg_1240, "tmp_113_reg_1240");
    sc_trace(mVcdFile, tmp_359_reg_1245, "tmp_359_reg_1245");
    sc_trace(mVcdFile, tmp_227_2_fu_628_p2, "tmp_227_2_fu_628_p2");
    sc_trace(mVcdFile, tmp_227_2_reg_1250, "tmp_227_2_reg_1250");
    sc_trace(mVcdFile, tmp_118_reg_1255, "tmp_118_reg_1255");
    sc_trace(mVcdFile, tmp_362_reg_1260, "tmp_362_reg_1260");
    sc_trace(mVcdFile, tmp_227_3_fu_698_p2, "tmp_227_3_fu_698_p2");
    sc_trace(mVcdFile, tmp_227_3_reg_1265, "tmp_227_3_reg_1265");
    sc_trace(mVcdFile, p_Val2_s_fu_881_p2, "p_Val2_s_fu_881_p2");
    sc_trace(mVcdFile, p_Val2_s_reg_1270, "p_Val2_s_reg_1270");
    sc_trace(mVcdFile, p_Val2_22_1_fu_956_p2, "p_Val2_22_1_fu_956_p2");
    sc_trace(mVcdFile, p_Val2_22_1_reg_1275, "p_Val2_22_1_reg_1275");
    sc_trace(mVcdFile, p_Val2_22_2_fu_1031_p2, "p_Val2_22_2_fu_1031_p2");
    sc_trace(mVcdFile, p_Val2_22_2_reg_1280, "p_Val2_22_2_reg_1280");
    sc_trace(mVcdFile, p_Val2_22_3_fu_1106_p2, "p_Val2_22_3_fu_1106_p2");
    sc_trace(mVcdFile, p_Val2_22_3_reg_1285, "p_Val2_22_3_reg_1285");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, tmp_99_fu_413_p1, "tmp_99_fu_413_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, macRegisters_0_V_4_fu_104, "macRegisters_0_V_4_fu_104");
    sc_trace(mVcdFile, macRegisters_0_V_fu_730_p2, "macRegisters_0_V_fu_730_p2");
    sc_trace(mVcdFile, macRegisters_1_V_4_fu_108, "macRegisters_1_V_4_fu_108");
    sc_trace(mVcdFile, macRegisters_1_V_fu_749_p2, "macRegisters_1_V_fu_749_p2");
    sc_trace(mVcdFile, macRegisters_2_V_4_fu_112, "macRegisters_2_V_4_fu_112");
    sc_trace(mVcdFile, macRegisters_2_V_fu_768_p2, "macRegisters_2_V_fu_768_p2");
    sc_trace(mVcdFile, macRegisters_3_V_4_fu_116, "macRegisters_3_V_4_fu_116");
    sc_trace(mVcdFile, macRegisters_3_V_fu_787_p2, "macRegisters_3_V_fu_787_p2");
    sc_trace(mVcdFile, tmp_fu_249_p1, "tmp_fu_249_p1");
    sc_trace(mVcdFile, exitcond_flatten_fu_273_p2, "exitcond_flatten_fu_273_p2");
    sc_trace(mVcdFile, tmp_96_fu_253_p3, "tmp_96_fu_253_p3");
    sc_trace(mVcdFile, tmp_292_fu_309_p2, "tmp_292_fu_309_p2");
    sc_trace(mVcdFile, not_exitcond_flatten_fu_303_p2, "not_exitcond_flatten_fu_303_p2");
    sc_trace(mVcdFile, nm_mid_fu_279_p3, "nm_mid_fu_279_p3");
    sc_trace(mVcdFile, tmp_97_mid_fu_315_p2, "tmp_97_mid_fu_315_p2");
    sc_trace(mVcdFile, tmp_274_fu_327_p2, "tmp_274_fu_327_p2");
    sc_trace(mVcdFile, nm_2_fu_321_p2, "nm_2_fu_321_p2");
    sc_trace(mVcdFile, tmp_351_fu_341_p1, "tmp_351_fu_341_p1");
    sc_trace(mVcdFile, tmp_96_mid1_fu_345_p3, "tmp_96_mid1_fu_345_p3");
    sc_trace(mVcdFile, tmp_96_mid_fu_287_p3, "tmp_96_mid_fu_287_p3");
    sc_trace(mVcdFile, nm_t_mid_fu_295_p3, "nm_t_mid_fu_295_p3");
    sc_trace(mVcdFile, sf_mid2_fu_333_p3, "sf_mid2_fu_333_p3");
    sc_trace(mVcdFile, sf_cast1_fu_377_p1, "sf_cast1_fu_377_p1");
    sc_trace(mVcdFile, tmp_96_mid2_fu_353_p3, "tmp_96_mid2_fu_353_p3");
    sc_trace(mVcdFile, indvar_flatten_op_fu_399_p2, "indvar_flatten_op_fu_399_p2");
    sc_trace(mVcdFile, p_Val2_s_136_fu_428_p0, "p_Val2_s_136_fu_428_p0");
    sc_trace(mVcdFile, p_Val2_s_136_fu_428_p1, "p_Val2_s_136_fu_428_p1");
    sc_trace(mVcdFile, p_08_cast_fu_420_p1, "p_08_cast_fu_420_p1");
    sc_trace(mVcdFile, p_Val2_s_136_fu_428_p2, "p_Val2_s_136_fu_428_p2");
    sc_trace(mVcdFile, tmp_354_fu_460_p1, "tmp_354_fu_460_p1");
    sc_trace(mVcdFile, tmp_352_fu_434_p3, "tmp_352_fu_434_p3");
    sc_trace(mVcdFile, tmp_104_fu_470_p4, "tmp_104_fu_470_p4");
    sc_trace(mVcdFile, tmp_103_fu_464_p2, "tmp_103_fu_464_p2");
    sc_trace(mVcdFile, tmp_105_fu_480_p3, "tmp_105_fu_480_p3");
    sc_trace(mVcdFile, p_Val2_1_fu_498_p0, "p_Val2_1_fu_498_p0");
    sc_trace(mVcdFile, p_Val2_1_fu_498_p1, "p_Val2_1_fu_498_p1");
    sc_trace(mVcdFile, p_Val2_1_fu_498_p2, "p_Val2_1_fu_498_p2");
    sc_trace(mVcdFile, tmp_357_fu_530_p1, "tmp_357_fu_530_p1");
    sc_trace(mVcdFile, tmp_355_fu_504_p3, "tmp_355_fu_504_p3");
    sc_trace(mVcdFile, tmp_111_fu_540_p4, "tmp_111_fu_540_p4");
    sc_trace(mVcdFile, tmp_110_fu_534_p2, "tmp_110_fu_534_p2");
    sc_trace(mVcdFile, tmp_112_fu_550_p3, "tmp_112_fu_550_p3");
    sc_trace(mVcdFile, p_Val2_2_fu_568_p0, "p_Val2_2_fu_568_p0");
    sc_trace(mVcdFile, p_Val2_2_fu_568_p1, "p_Val2_2_fu_568_p1");
    sc_trace(mVcdFile, p_Val2_2_fu_568_p2, "p_Val2_2_fu_568_p2");
    sc_trace(mVcdFile, tmp_360_fu_600_p1, "tmp_360_fu_600_p1");
    sc_trace(mVcdFile, tmp_358_fu_574_p3, "tmp_358_fu_574_p3");
    sc_trace(mVcdFile, tmp_116_fu_610_p4, "tmp_116_fu_610_p4");
    sc_trace(mVcdFile, tmp_115_fu_604_p2, "tmp_115_fu_604_p2");
    sc_trace(mVcdFile, tmp_117_fu_620_p3, "tmp_117_fu_620_p3");
    sc_trace(mVcdFile, p_Val2_3_fu_638_p0, "p_Val2_3_fu_638_p0");
    sc_trace(mVcdFile, p_Val2_3_fu_638_p1, "p_Val2_3_fu_638_p1");
    sc_trace(mVcdFile, p_Val2_3_fu_638_p2, "p_Val2_3_fu_638_p2");
    sc_trace(mVcdFile, tmp_363_fu_670_p1, "tmp_363_fu_670_p1");
    sc_trace(mVcdFile, tmp_361_fu_644_p3, "tmp_361_fu_644_p3");
    sc_trace(mVcdFile, tmp_121_fu_680_p4, "tmp_121_fu_680_p4");
    sc_trace(mVcdFile, tmp_120_fu_674_p2, "tmp_120_fu_674_p2");
    sc_trace(mVcdFile, tmp_122_fu_690_p3, "tmp_122_fu_690_p3");
    sc_trace(mVcdFile, qb_assign_2_fu_716_p2, "qb_assign_2_fu_716_p2");
    sc_trace(mVcdFile, tmp_107_fu_720_p1, "tmp_107_fu_720_p1");
    sc_trace(mVcdFile, tmp1_fu_724_p2, "tmp1_fu_724_p2");
    sc_trace(mVcdFile, qb_assign_2_1_fu_735_p2, "qb_assign_2_1_fu_735_p2");
    sc_trace(mVcdFile, tmp_228_1_fu_739_p1, "tmp_228_1_fu_739_p1");
    sc_trace(mVcdFile, tmp2_fu_743_p2, "tmp2_fu_743_p2");
    sc_trace(mVcdFile, qb_assign_2_2_fu_754_p2, "qb_assign_2_2_fu_754_p2");
    sc_trace(mVcdFile, tmp_228_2_fu_758_p1, "tmp_228_2_fu_758_p1");
    sc_trace(mVcdFile, tmp3_fu_762_p2, "tmp3_fu_762_p2");
    sc_trace(mVcdFile, qb_assign_2_3_fu_773_p2, "qb_assign_2_3_fu_773_p2");
    sc_trace(mVcdFile, tmp_228_3_fu_777_p1, "tmp_228_3_fu_777_p1");
    sc_trace(mVcdFile, tmp4_fu_781_p2, "tmp4_fu_781_p2");
    sc_trace(mVcdFile, tmp_123_fu_812_p34, "tmp_123_fu_812_p34");
    sc_trace(mVcdFile, tmp_124_fu_887_p34, "tmp_124_fu_887_p34");
    sc_trace(mVcdFile, tmp_125_fu_962_p34, "tmp_125_fu_962_p34");
    sc_trace(mVcdFile, tmp_126_fu_1037_p34, "tmp_126_fu_1037_p34");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

Conv1DMac_new_1::~Conv1DMac_new_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete weights10_m_weights_3_U;
    delete weights10_m_weights_2_U;
    delete weights10_m_weights_1_U;
    delete weights10_m_weights_s_U;
    delete computeS2_mux_325yd2_x_x_x_x_U125;
    delete computeS2_mux_325yd2_x_x_x_x_U126;
    delete computeS2_mux_325yd2_x_x_x_x_U127;
    delete computeS2_mux_325yd2_x_x_x_x_U128;
}

void Conv1DMac_new_1::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv8_0;
}

void Conv1DMac_new_1::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv8_1;
}

void Conv1DMac_new_1::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv8_FF;
}

void Conv1DMac_new_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        } else if ((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_enable_reg_pp0_iter4 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten6_fu_261_p2.read()))) {
        indvar_flatten6_reg_185 = indvar_flatten_next6_fu_267_p2.read();
    } else if ((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        indvar_flatten6_reg_185 = ap_const_lv20_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten6_fu_261_p2.read()))) {
        indvar_flatten_reg_196 = indvar_flatten_next_fu_405_p3.read();
    } else if ((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        indvar_flatten_reg_196 = ap_const_lv14_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_100_reg_1176_pp0_iter2_reg.read()))) {
        macRegisters_0_V_4_fu_104 = macRegisters_0_V_fu_730_p2.read();
    } else if (((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, tmp_100_reg_1176_pp0_iter2_reg.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read())))) {
        macRegisters_0_V_4_fu_104 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_100_reg_1176_pp0_iter2_reg.read()))) {
        macRegisters_1_V_4_fu_108 = macRegisters_1_V_fu_749_p2.read();
    } else if (((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, tmp_100_reg_1176_pp0_iter2_reg.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read())))) {
        macRegisters_1_V_4_fu_108 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_100_reg_1176_pp0_iter2_reg.read()))) {
        macRegisters_2_V_4_fu_112 = macRegisters_2_V_fu_768_p2.read();
    } else if (((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, tmp_100_reg_1176_pp0_iter2_reg.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read())))) {
        macRegisters_2_V_4_fu_112 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_100_reg_1176_pp0_iter2_reg.read()))) {
        macRegisters_3_V_4_fu_116 = macRegisters_3_V_fu_787_p2.read();
    } else if (((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, tmp_100_reg_1176_pp0_iter2_reg.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read())))) {
        macRegisters_3_V_4_fu_116 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten6_fu_261_p2.read()))) {
        nm_reg_207 = nm_mid2_fu_369_p3.read();
    } else if ((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        nm_reg_207 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten6_fu_261_p2.read()))) {
        sf_reg_218 = sf_2_fu_393_p2.read();
    } else if ((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        sf_reg_218 = ap_const_lv8_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_flatten6_reg_1149 = exitcond_flatten6_fu_261_p2.read();
        exitcond_flatten6_reg_1149_pp0_iter1_reg = exitcond_flatten6_reg_1149.read();
        nm_t_mid2_reg_1158_pp0_iter1_reg = nm_t_mid2_reg_1158.read();
        tmp_100_reg_1176_pp0_iter1_reg = tmp_100_reg_1176.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten6_fu_261_p2.read()))) {
        nm_t_mid2_reg_1158 = nm_t_mid2_fu_361_p3.read();
        tmp_100_reg_1176 = tmp_100_fu_387_p2.read();
        tmp_98_reg_1171 = tmp_98_fu_381_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        nm_t_mid2_reg_1158_pp0_iter2_reg = nm_t_mid2_reg_1158_pp0_iter1_reg.read();
        tmp_100_reg_1176_pp0_iter2_reg = tmp_100_reg_1176_pp0_iter1_reg.read();
        tmp_100_reg_1176_pp0_iter3_reg = tmp_100_reg_1176_pp0_iter2_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_100_reg_1176_pp0_iter2_reg.read()))) {
        p_Val2_22_1_reg_1275 = p_Val2_22_1_fu_956_p2.read();
        p_Val2_22_2_reg_1280 = p_Val2_22_2_fu_1031_p2.read();
        p_Val2_22_3_reg_1285 = p_Val2_22_3_fu_1106_p2.read();
        p_Val2_s_reg_1270 = p_Val2_s_fu_881_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_flatten6_reg_1149_pp0_iter1_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_101_reg_1210 = p_Val2_s_136_fu_428_p2.read().range(14, 7);
        tmp_106_reg_1220 = tmp_106_fu_488_p2.read();
        tmp_108_reg_1225 = p_Val2_1_fu_498_p2.read().range(14, 7);
        tmp_113_reg_1240 = p_Val2_2_fu_568_p2.read().range(14, 7);
        tmp_118_reg_1255 = p_Val2_3_fu_638_p2.read().range(14, 7);
        tmp_227_1_reg_1235 = tmp_227_1_fu_558_p2.read();
        tmp_227_2_reg_1250 = tmp_227_2_fu_628_p2.read();
        tmp_227_3_reg_1265 = tmp_227_3_fu_698_p2.read();
        tmp_353_reg_1215 = p_Val2_s_136_fu_428_p2.read().range(6, 6);
        tmp_356_reg_1230 = p_Val2_1_fu_498_p2.read().range(6, 6);
        tmp_359_reg_1245 = p_Val2_2_fu_568_p2.read().range(6, 6);
        tmp_362_reg_1260 = p_Val2_3_fu_638_p2.read().range(6, 6);
    }
}

void Conv1DMac_new_1::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void Conv1DMac_new_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Conv1DMac_new_1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[2];
}

void Conv1DMac_new_1::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Conv1DMac_new_1::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(exitcond_flatten6_reg_1149_pp0_iter1_reg.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(tmp_100_reg_1176_pp0_iter3_reg.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read())));
}

void Conv1DMac_new_1::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(exitcond_flatten6_reg_1149_pp0_iter1_reg.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(tmp_100_reg_1176_pp0_iter3_reg.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read())));
}

void Conv1DMac_new_1::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(exitcond_flatten6_reg_1149_pp0_iter1_reg.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(tmp_100_reg_1176_pp0_iter3_reg.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read())));
}

void Conv1DMac_new_1::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void Conv1DMac_new_1::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Conv1DMac_new_1::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Conv1DMac_new_1::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = (esl_seteq<1,1,1>(exitcond_flatten6_reg_1149_pp0_iter1_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read()));
}

void Conv1DMac_new_1::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void Conv1DMac_new_1::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = (esl_seteq<1,1,1>(tmp_100_reg_1176_pp0_iter3_reg.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, out_V_V_full_n.read()));
}

void Conv1DMac_new_1::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(exitcond_flatten6_fu_261_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void Conv1DMac_new_1::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void Conv1DMac_new_1::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void Conv1DMac_new_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Conv1DMac_new_1::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void Conv1DMac_new_1::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void Conv1DMac_new_1::thread_exitcond_flatten6_fu_261_p2() {
    exitcond_flatten6_fu_261_p2 = (!indvar_flatten6_reg_185.read().is_01() || !ap_const_lv20_80000.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten6_reg_185.read() == ap_const_lv20_80000);
}

void Conv1DMac_new_1::thread_exitcond_flatten_fu_273_p2() {
    exitcond_flatten_fu_273_p2 = (!indvar_flatten_reg_196.read().is_01() || !ap_const_lv14_1000.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_196.read() == ap_const_lv14_1000);
}

void Conv1DMac_new_1::thread_in_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten6_reg_1149_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        in_V_V_blk_n = in_V_V_empty_n.read();
    } else {
        in_V_V_blk_n = ap_const_logic_1;
    }
}

void Conv1DMac_new_1::thread_in_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten6_reg_1149_pp0_iter1_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        in_V_V_read = ap_const_logic_1;
    } else {
        in_V_V_read = ap_const_logic_0;
    }
}

void Conv1DMac_new_1::thread_indvar_flatten_next6_fu_267_p2() {
    indvar_flatten_next6_fu_267_p2 = (!ap_const_lv20_1.is_01() || !indvar_flatten6_reg_185.read().is_01())? sc_lv<20>(): (sc_biguint<20>(ap_const_lv20_1) + sc_biguint<20>(indvar_flatten6_reg_185.read()));
}

void Conv1DMac_new_1::thread_indvar_flatten_next_fu_405_p3() {
    indvar_flatten_next_fu_405_p3 = (!exitcond_flatten_fu_273_p2.read()[0].is_01())? sc_lv<14>(): ((exitcond_flatten_fu_273_p2.read()[0].to_bool())? ap_const_lv14_1: indvar_flatten_op_fu_399_p2.read());
}

void Conv1DMac_new_1::thread_indvar_flatten_op_fu_399_p2() {
    indvar_flatten_op_fu_399_p2 = (!indvar_flatten_reg_196.read().is_01() || !ap_const_lv14_1.is_01())? sc_lv<14>(): (sc_biguint<14>(indvar_flatten_reg_196.read()) + sc_biguint<14>(ap_const_lv14_1));
}

void Conv1DMac_new_1::thread_internal_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void Conv1DMac_new_1::thread_macRegisters_0_V_fu_730_p2() {
    macRegisters_0_V_fu_730_p2 = (!tmp_101_reg_1210.read().is_01() || !tmp1_fu_724_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_101_reg_1210.read()) + sc_biguint<8>(tmp1_fu_724_p2.read()));
}

void Conv1DMac_new_1::thread_macRegisters_1_V_fu_749_p2() {
    macRegisters_1_V_fu_749_p2 = (!tmp_108_reg_1225.read().is_01() || !tmp2_fu_743_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_108_reg_1225.read()) + sc_biguint<8>(tmp2_fu_743_p2.read()));
}

void Conv1DMac_new_1::thread_macRegisters_2_V_fu_768_p2() {
    macRegisters_2_V_fu_768_p2 = (!tmp_113_reg_1240.read().is_01() || !tmp3_fu_762_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_113_reg_1240.read()) + sc_biguint<8>(tmp3_fu_762_p2.read()));
}

void Conv1DMac_new_1::thread_macRegisters_3_V_fu_787_p2() {
    macRegisters_3_V_fu_787_p2 = (!tmp_118_reg_1255.read().is_01() || !tmp4_fu_781_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_118_reg_1255.read()) + sc_biguint<8>(tmp4_fu_781_p2.read()));
}

void Conv1DMac_new_1::thread_nm_2_fu_321_p2() {
    nm_2_fu_321_p2 = (!ap_const_lv6_1.is_01() || !nm_mid_fu_279_p3.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(nm_mid_fu_279_p3.read()));
}

void Conv1DMac_new_1::thread_nm_mid2_fu_369_p3() {
    nm_mid2_fu_369_p3 = (!tmp_97_mid_fu_315_p2.read()[0].is_01())? sc_lv<6>(): ((tmp_97_mid_fu_315_p2.read()[0].to_bool())? nm_2_fu_321_p2.read(): nm_mid_fu_279_p3.read());
}

void Conv1DMac_new_1::thread_nm_mid_fu_279_p3() {
    nm_mid_fu_279_p3 = (!exitcond_flatten_fu_273_p2.read()[0].is_01())? sc_lv<6>(): ((exitcond_flatten_fu_273_p2.read()[0].to_bool())? ap_const_lv6_0: nm_reg_207.read());
}

void Conv1DMac_new_1::thread_nm_t_mid2_fu_361_p3() {
    nm_t_mid2_fu_361_p3 = (!tmp_97_mid_fu_315_p2.read()[0].is_01())? sc_lv<5>(): ((tmp_97_mid_fu_315_p2.read()[0].to_bool())? tmp_351_fu_341_p1.read(): nm_t_mid_fu_295_p3.read());
}

void Conv1DMac_new_1::thread_nm_t_mid_fu_295_p3() {
    nm_t_mid_fu_295_p3 = (!exitcond_flatten_fu_273_p2.read()[0].is_01())? sc_lv<5>(): ((exitcond_flatten_fu_273_p2.read()[0].to_bool())? ap_const_lv5_0: tmp_fu_249_p1.read());
}

void Conv1DMac_new_1::thread_not_exitcond_flatten_fu_303_p2() {
    not_exitcond_flatten_fu_303_p2 = (exitcond_flatten_fu_273_p2.read() ^ ap_const_lv1_1);
}

void Conv1DMac_new_1::thread_out_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(tmp_100_reg_1176_pp0_iter3_reg.read(), ap_const_lv1_1))) {
        out_V_V_blk_n = out_V_V_full_n.read();
    } else {
        out_V_V_blk_n = ap_const_logic_1;
    }
}

void Conv1DMac_new_1::thread_out_V_V_din() {
    out_V_V_din = esl_concat<24,8>(esl_concat<16,8>(esl_concat<8,8>(p_Val2_22_3_reg_1285.read(), p_Val2_22_2_reg_1280.read()), p_Val2_22_1_reg_1275.read()), p_Val2_s_reg_1270.read());
}

void Conv1DMac_new_1::thread_out_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(tmp_100_reg_1176_pp0_iter3_reg.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        out_V_V_write = ap_const_logic_1;
    } else {
        out_V_V_write = ap_const_logic_0;
    }
}

void Conv1DMac_new_1::thread_p_08_cast_fu_420_p1() {
    p_08_cast_fu_420_p1 = esl_sext<15,8>(in_V_V_dout.read());
}

void Conv1DMac_new_1::thread_p_Val2_1_fu_498_p0() {
    p_Val2_1_fu_498_p0 = weights10_m_weights_2_q0.read();
}

void Conv1DMac_new_1::thread_p_Val2_1_fu_498_p1() {
    p_Val2_1_fu_498_p1 =  (sc_lv<8>) (p_08_cast_fu_420_p1.read());
}

void Conv1DMac_new_1::thread_p_Val2_1_fu_498_p2() {
    p_Val2_1_fu_498_p2 = (!p_Val2_1_fu_498_p0.read().is_01() || !p_Val2_1_fu_498_p1.read().is_01())? sc_lv<15>(): sc_bigint<7>(p_Val2_1_fu_498_p0.read()) * sc_bigint<8>(p_Val2_1_fu_498_p1.read());
}

void Conv1DMac_new_1::thread_p_Val2_22_1_fu_956_p2() {
    p_Val2_22_1_fu_956_p2 = (!macRegisters_1_V_fu_749_p2.read().is_01() || !tmp_124_fu_887_p34.read().is_01())? sc_lv<8>(): (sc_biguint<8>(macRegisters_1_V_fu_749_p2.read()) + sc_biguint<8>(tmp_124_fu_887_p34.read()));
}

void Conv1DMac_new_1::thread_p_Val2_22_2_fu_1031_p2() {
    p_Val2_22_2_fu_1031_p2 = (!macRegisters_2_V_fu_768_p2.read().is_01() || !tmp_125_fu_962_p34.read().is_01())? sc_lv<8>(): (sc_biguint<8>(macRegisters_2_V_fu_768_p2.read()) + sc_biguint<8>(tmp_125_fu_962_p34.read()));
}

void Conv1DMac_new_1::thread_p_Val2_22_3_fu_1106_p2() {
    p_Val2_22_3_fu_1106_p2 = (!macRegisters_3_V_fu_787_p2.read().is_01() || !tmp_126_fu_1037_p34.read().is_01())? sc_lv<8>(): (sc_biguint<8>(macRegisters_3_V_fu_787_p2.read()) + sc_biguint<8>(tmp_126_fu_1037_p34.read()));
}

void Conv1DMac_new_1::thread_p_Val2_2_fu_568_p0() {
    p_Val2_2_fu_568_p0 = weights10_m_weights_1_q0.read();
}

void Conv1DMac_new_1::thread_p_Val2_2_fu_568_p1() {
    p_Val2_2_fu_568_p1 =  (sc_lv<8>) (p_08_cast_fu_420_p1.read());
}

void Conv1DMac_new_1::thread_p_Val2_2_fu_568_p2() {
    p_Val2_2_fu_568_p2 = (!p_Val2_2_fu_568_p0.read().is_01() || !p_Val2_2_fu_568_p1.read().is_01())? sc_lv<15>(): sc_bigint<7>(p_Val2_2_fu_568_p0.read()) * sc_bigint<8>(p_Val2_2_fu_568_p1.read());
}

void Conv1DMac_new_1::thread_p_Val2_3_fu_638_p0() {
    p_Val2_3_fu_638_p0 = weights10_m_weights_s_q0.read();
}

void Conv1DMac_new_1::thread_p_Val2_3_fu_638_p1() {
    p_Val2_3_fu_638_p1 =  (sc_lv<8>) (p_08_cast_fu_420_p1.read());
}

void Conv1DMac_new_1::thread_p_Val2_3_fu_638_p2() {
    p_Val2_3_fu_638_p2 = (!p_Val2_3_fu_638_p0.read().is_01() || !p_Val2_3_fu_638_p1.read().is_01())? sc_lv<15>(): sc_bigint<7>(p_Val2_3_fu_638_p0.read()) * sc_bigint<8>(p_Val2_3_fu_638_p1.read());
}

void Conv1DMac_new_1::thread_p_Val2_s_136_fu_428_p0() {
    p_Val2_s_136_fu_428_p0 = weights10_m_weights_3_q0.read();
}

void Conv1DMac_new_1::thread_p_Val2_s_136_fu_428_p1() {
    p_Val2_s_136_fu_428_p1 =  (sc_lv<8>) (p_08_cast_fu_420_p1.read());
}

void Conv1DMac_new_1::thread_p_Val2_s_136_fu_428_p2() {
    p_Val2_s_136_fu_428_p2 = (!p_Val2_s_136_fu_428_p0.read().is_01() || !p_Val2_s_136_fu_428_p1.read().is_01())? sc_lv<15>(): sc_bigint<7>(p_Val2_s_136_fu_428_p0.read()) * sc_bigint<8>(p_Val2_s_136_fu_428_p1.read());
}

void Conv1DMac_new_1::thread_p_Val2_s_fu_881_p2() {
    p_Val2_s_fu_881_p2 = (!macRegisters_0_V_fu_730_p2.read().is_01() || !tmp_123_fu_812_p34.read().is_01())? sc_lv<8>(): (sc_biguint<8>(macRegisters_0_V_fu_730_p2.read()) + sc_biguint<8>(tmp_123_fu_812_p34.read()));
}

void Conv1DMac_new_1::thread_qb_assign_2_1_fu_735_p2() {
    qb_assign_2_1_fu_735_p2 = (tmp_227_1_reg_1235.read() & tmp_356_reg_1230.read());
}

void Conv1DMac_new_1::thread_qb_assign_2_2_fu_754_p2() {
    qb_assign_2_2_fu_754_p2 = (tmp_227_2_reg_1250.read() & tmp_359_reg_1245.read());
}

void Conv1DMac_new_1::thread_qb_assign_2_3_fu_773_p2() {
    qb_assign_2_3_fu_773_p2 = (tmp_227_3_reg_1265.read() & tmp_362_reg_1260.read());
}

void Conv1DMac_new_1::thread_qb_assign_2_fu_716_p2() {
    qb_assign_2_fu_716_p2 = (tmp_106_reg_1220.read() & tmp_353_reg_1215.read());
}

void Conv1DMac_new_1::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void Conv1DMac_new_1::thread_sf_2_fu_393_p2() {
    sf_2_fu_393_p2 = (!sf_mid2_fu_333_p3.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(sf_mid2_fu_333_p3.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void Conv1DMac_new_1::thread_sf_cast1_fu_377_p1() {
    sf_cast1_fu_377_p1 = esl_zext<12,8>(sf_mid2_fu_333_p3.read());
}

void Conv1DMac_new_1::thread_sf_mid2_fu_333_p3() {
    sf_mid2_fu_333_p3 = (!tmp_274_fu_327_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_274_fu_327_p2.read()[0].to_bool())? ap_const_lv8_0: sf_reg_218.read());
}

void Conv1DMac_new_1::thread_start_out() {
    start_out = real_start.read();
}

void Conv1DMac_new_1::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void Conv1DMac_new_1::thread_tmp1_fu_724_p2() {
    tmp1_fu_724_p2 = (!tmp_107_fu_720_p1.read().is_01() || !macRegisters_0_V_4_fu_104.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_107_fu_720_p1.read()) + sc_biguint<8>(macRegisters_0_V_4_fu_104.read()));
}

void Conv1DMac_new_1::thread_tmp2_fu_743_p2() {
    tmp2_fu_743_p2 = (!tmp_228_1_fu_739_p1.read().is_01() || !macRegisters_1_V_4_fu_108.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_228_1_fu_739_p1.read()) + sc_biguint<8>(macRegisters_1_V_4_fu_108.read()));
}

void Conv1DMac_new_1::thread_tmp3_fu_762_p2() {
    tmp3_fu_762_p2 = (!tmp_228_2_fu_758_p1.read().is_01() || !macRegisters_2_V_4_fu_112.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_228_2_fu_758_p1.read()) + sc_biguint<8>(macRegisters_2_V_4_fu_112.read()));
}

void Conv1DMac_new_1::thread_tmp4_fu_781_p2() {
    tmp4_fu_781_p2 = (!tmp_228_3_fu_777_p1.read().is_01() || !macRegisters_3_V_4_fu_116.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_228_3_fu_777_p1.read()) + sc_biguint<8>(macRegisters_3_V_4_fu_116.read()));
}

void Conv1DMac_new_1::thread_tmp_100_fu_387_p2() {
    tmp_100_fu_387_p2 = (!sf_mid2_fu_333_p3.read().is_01() || !ap_const_lv8_7F.is_01())? sc_lv<1>(): sc_lv<1>(sf_mid2_fu_333_p3.read() == ap_const_lv8_7F);
}

void Conv1DMac_new_1::thread_tmp_103_fu_464_p2() {
    tmp_103_fu_464_p2 = (tmp_354_fu_460_p1.read() | tmp_352_fu_434_p3.read());
}

void Conv1DMac_new_1::thread_tmp_104_fu_470_p4() {
    tmp_104_fu_470_p4 = p_Val2_s_136_fu_428_p2.read().range(5, 1);
}

void Conv1DMac_new_1::thread_tmp_105_fu_480_p3() {
    tmp_105_fu_480_p3 = esl_concat<5,1>(tmp_104_fu_470_p4.read(), tmp_103_fu_464_p2.read());
}

void Conv1DMac_new_1::thread_tmp_106_fu_488_p2() {
    tmp_106_fu_488_p2 = (!tmp_105_fu_480_p3.read().is_01() || !ap_const_lv6_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_105_fu_480_p3.read() != ap_const_lv6_0);
}

void Conv1DMac_new_1::thread_tmp_107_fu_720_p1() {
    tmp_107_fu_720_p1 = esl_zext<8,1>(qb_assign_2_fu_716_p2.read());
}

void Conv1DMac_new_1::thread_tmp_110_fu_534_p2() {
    tmp_110_fu_534_p2 = (tmp_357_fu_530_p1.read() | tmp_355_fu_504_p3.read());
}

void Conv1DMac_new_1::thread_tmp_111_fu_540_p4() {
    tmp_111_fu_540_p4 = p_Val2_1_fu_498_p2.read().range(5, 1);
}

void Conv1DMac_new_1::thread_tmp_112_fu_550_p3() {
    tmp_112_fu_550_p3 = esl_concat<5,1>(tmp_111_fu_540_p4.read(), tmp_110_fu_534_p2.read());
}

void Conv1DMac_new_1::thread_tmp_115_fu_604_p2() {
    tmp_115_fu_604_p2 = (tmp_360_fu_600_p1.read() | tmp_358_fu_574_p3.read());
}

void Conv1DMac_new_1::thread_tmp_116_fu_610_p4() {
    tmp_116_fu_610_p4 = p_Val2_2_fu_568_p2.read().range(5, 1);
}

void Conv1DMac_new_1::thread_tmp_117_fu_620_p3() {
    tmp_117_fu_620_p3 = esl_concat<5,1>(tmp_116_fu_610_p4.read(), tmp_115_fu_604_p2.read());
}

void Conv1DMac_new_1::thread_tmp_120_fu_674_p2() {
    tmp_120_fu_674_p2 = (tmp_363_fu_670_p1.read() | tmp_361_fu_644_p3.read());
}

void Conv1DMac_new_1::thread_tmp_121_fu_680_p4() {
    tmp_121_fu_680_p4 = p_Val2_3_fu_638_p2.read().range(5, 1);
}

void Conv1DMac_new_1::thread_tmp_122_fu_690_p3() {
    tmp_122_fu_690_p3 = esl_concat<5,1>(tmp_121_fu_680_p4.read(), tmp_120_fu_674_p2.read());
}

void Conv1DMac_new_1::thread_tmp_227_1_fu_558_p2() {
    tmp_227_1_fu_558_p2 = (!tmp_112_fu_550_p3.read().is_01() || !ap_const_lv6_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_112_fu_550_p3.read() != ap_const_lv6_0);
}

void Conv1DMac_new_1::thread_tmp_227_2_fu_628_p2() {
    tmp_227_2_fu_628_p2 = (!tmp_117_fu_620_p3.read().is_01() || !ap_const_lv6_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_117_fu_620_p3.read() != ap_const_lv6_0);
}

void Conv1DMac_new_1::thread_tmp_227_3_fu_698_p2() {
    tmp_227_3_fu_698_p2 = (!tmp_122_fu_690_p3.read().is_01() || !ap_const_lv6_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_122_fu_690_p3.read() != ap_const_lv6_0);
}

void Conv1DMac_new_1::thread_tmp_228_1_fu_739_p1() {
    tmp_228_1_fu_739_p1 = esl_zext<8,1>(qb_assign_2_1_fu_735_p2.read());
}

void Conv1DMac_new_1::thread_tmp_228_2_fu_758_p1() {
    tmp_228_2_fu_758_p1 = esl_zext<8,1>(qb_assign_2_2_fu_754_p2.read());
}

void Conv1DMac_new_1::thread_tmp_228_3_fu_777_p1() {
    tmp_228_3_fu_777_p1 = esl_zext<8,1>(qb_assign_2_3_fu_773_p2.read());
}

void Conv1DMac_new_1::thread_tmp_274_fu_327_p2() {
    tmp_274_fu_327_p2 = (tmp_97_mid_fu_315_p2.read() | exitcond_flatten_fu_273_p2.read());
}

void Conv1DMac_new_1::thread_tmp_292_fu_309_p2() {
    tmp_292_fu_309_p2 = (!sf_reg_218.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(sf_reg_218.read() == ap_const_lv8_80);
}

void Conv1DMac_new_1::thread_tmp_351_fu_341_p1() {
    tmp_351_fu_341_p1 = nm_2_fu_321_p2.read().range(5-1, 0);
}

void Conv1DMac_new_1::thread_tmp_352_fu_434_p3() {
    tmp_352_fu_434_p3 = p_Val2_s_136_fu_428_p2.read().range(14, 14);
}

void Conv1DMac_new_1::thread_tmp_354_fu_460_p1() {
    tmp_354_fu_460_p1 = p_Val2_s_136_fu_428_p2.read().range(1-1, 0);
}

void Conv1DMac_new_1::thread_tmp_355_fu_504_p3() {
    tmp_355_fu_504_p3 = p_Val2_1_fu_498_p2.read().range(14, 14);
}

void Conv1DMac_new_1::thread_tmp_357_fu_530_p1() {
    tmp_357_fu_530_p1 = p_Val2_1_fu_498_p2.read().range(1-1, 0);
}

void Conv1DMac_new_1::thread_tmp_358_fu_574_p3() {
    tmp_358_fu_574_p3 = p_Val2_2_fu_568_p2.read().range(14, 14);
}

void Conv1DMac_new_1::thread_tmp_360_fu_600_p1() {
    tmp_360_fu_600_p1 = p_Val2_2_fu_568_p2.read().range(1-1, 0);
}

void Conv1DMac_new_1::thread_tmp_361_fu_644_p3() {
    tmp_361_fu_644_p3 = p_Val2_3_fu_638_p2.read().range(14, 14);
}

void Conv1DMac_new_1::thread_tmp_363_fu_670_p1() {
    tmp_363_fu_670_p1 = p_Val2_3_fu_638_p2.read().range(1-1, 0);
}

void Conv1DMac_new_1::thread_tmp_96_fu_253_p3() {
    tmp_96_fu_253_p3 = esl_concat<5,7>(tmp_fu_249_p1.read(), ap_const_lv7_0);
}

void Conv1DMac_new_1::thread_tmp_96_mid1_fu_345_p3() {
    tmp_96_mid1_fu_345_p3 = esl_concat<5,7>(tmp_351_fu_341_p1.read(), ap_const_lv7_0);
}

void Conv1DMac_new_1::thread_tmp_96_mid2_fu_353_p3() {
    tmp_96_mid2_fu_353_p3 = (!tmp_97_mid_fu_315_p2.read()[0].is_01())? sc_lv<12>(): ((tmp_97_mid_fu_315_p2.read()[0].to_bool())? tmp_96_mid1_fu_345_p3.read(): tmp_96_mid_fu_287_p3.read());
}

void Conv1DMac_new_1::thread_tmp_96_mid_fu_287_p3() {
    tmp_96_mid_fu_287_p3 = (!exitcond_flatten_fu_273_p2.read()[0].is_01())? sc_lv<12>(): ((exitcond_flatten_fu_273_p2.read()[0].to_bool())? ap_const_lv12_0: tmp_96_fu_253_p3.read());
}

void Conv1DMac_new_1::thread_tmp_97_mid_fu_315_p2() {
    tmp_97_mid_fu_315_p2 = (tmp_292_fu_309_p2.read() & not_exitcond_flatten_fu_303_p2.read());
}

void Conv1DMac_new_1::thread_tmp_98_fu_381_p2() {
    tmp_98_fu_381_p2 = (!sf_cast1_fu_377_p1.read().is_01() || !tmp_96_mid2_fu_353_p3.read().is_01())? sc_lv<12>(): (sc_biguint<12>(sf_cast1_fu_377_p1.read()) + sc_biguint<12>(tmp_96_mid2_fu_353_p3.read()));
}

void Conv1DMac_new_1::thread_tmp_99_fu_413_p1() {
    tmp_99_fu_413_p1 = esl_zext<64,12>(tmp_98_reg_1171.read());
}

void Conv1DMac_new_1::thread_tmp_fu_249_p1() {
    tmp_fu_249_p1 = nm_reg_207.read().range(5-1, 0);
}

void Conv1DMac_new_1::thread_weights10_m_weights_1_address0() {
    weights10_m_weights_1_address0 =  (sc_lv<12>) (tmp_99_fu_413_p1.read());
}

void Conv1DMac_new_1::thread_weights10_m_weights_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        weights10_m_weights_1_ce0 = ap_const_logic_1;
    } else {
        weights10_m_weights_1_ce0 = ap_const_logic_0;
    }
}

void Conv1DMac_new_1::thread_weights10_m_weights_2_address0() {
    weights10_m_weights_2_address0 =  (sc_lv<12>) (tmp_99_fu_413_p1.read());
}

void Conv1DMac_new_1::thread_weights10_m_weights_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        weights10_m_weights_2_ce0 = ap_const_logic_1;
    } else {
        weights10_m_weights_2_ce0 = ap_const_logic_0;
    }
}

void Conv1DMac_new_1::thread_weights10_m_weights_3_address0() {
    weights10_m_weights_3_address0 =  (sc_lv<12>) (tmp_99_fu_413_p1.read());
}

void Conv1DMac_new_1::thread_weights10_m_weights_3_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        weights10_m_weights_3_ce0 = ap_const_logic_1;
    } else {
        weights10_m_weights_3_ce0 = ap_const_logic_0;
    }
}

void Conv1DMac_new_1::thread_weights10_m_weights_s_address0() {
    weights10_m_weights_s_address0 =  (sc_lv<12>) (tmp_99_fu_413_p1.read());
}

void Conv1DMac_new_1::thread_weights10_m_weights_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        weights10_m_weights_s_ce0 = ap_const_logic_1;
    } else {
        weights10_m_weights_s_ce0 = ap_const_logic_0;
    }
}

void Conv1DMac_new_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(exitcond_flatten6_fu_261_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1)) && !(esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_1)) || (esl_seteq<1,1,1>(exitcond_flatten6_fu_261_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

