-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Conv1DMac_new is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    in_V_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    in_V_V_empty_n : IN STD_LOGIC;
    in_V_V_read : OUT STD_LOGIC;
    out_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_V_V_full_n : IN STD_LOGIC;
    out_V_V_write : OUT STD_LOGIC );
end;


architecture behav of Conv1DMac_new is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv23_400000 : STD_LOGIC_VECTOR (22 downto 0) := "10000000000000000000000";
    constant ap_const_lv23_1 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000001";
    constant ap_const_lv12_400 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv7_3F : STD_LOGIC_VECTOR (6 downto 0) := "0111111";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv8_21 : STD_LOGIC_VECTOR (7 downto 0) := "00100001";
    constant ap_const_lv8_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000111";
    constant ap_const_lv8_1D : STD_LOGIC_VECTOR (7 downto 0) := "00011101";
    constant ap_const_lv8_25 : STD_LOGIC_VECTOR (7 downto 0) := "00100101";
    constant ap_const_lv8_15 : STD_LOGIC_VECTOR (7 downto 0) := "00010101";
    constant ap_const_lv8_9 : STD_LOGIC_VECTOR (7 downto 0) := "00001001";
    constant ap_const_lv8_FC : STD_LOGIC_VECTOR (7 downto 0) := "11111100";
    constant ap_const_lv8_D : STD_LOGIC_VECTOR (7 downto 0) := "00001101";
    constant ap_const_lv8_8 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_const_lv8_24 : STD_LOGIC_VECTOR (7 downto 0) := "00100100";
    constant ap_const_lv8_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000110";
    constant ap_const_lv8_23 : STD_LOGIC_VECTOR (7 downto 0) := "00100011";
    constant ap_const_lv8_A : STD_LOGIC_VECTOR (7 downto 0) := "00001010";
    constant ap_const_lv8_F5 : STD_LOGIC_VECTOR (7 downto 0) := "11110101";
    constant ap_const_lv8_29 : STD_LOGIC_VECTOR (7 downto 0) := "00101001";
    constant ap_const_lv8_44 : STD_LOGIC_VECTOR (7 downto 0) := "01000100";
    constant ap_const_lv8_32 : STD_LOGIC_VECTOR (7 downto 0) := "00110010";
    constant ap_const_lv8_1B : STD_LOGIC_VECTOR (7 downto 0) := "00011011";
    constant ap_const_lv8_FE : STD_LOGIC_VECTOR (7 downto 0) := "11111110";
    constant ap_const_lv8_B : STD_LOGIC_VECTOR (7 downto 0) := "00001011";
    constant ap_const_lv8_C : STD_LOGIC_VECTOR (7 downto 0) := "00001100";
    constant ap_const_lv8_1C : STD_LOGIC_VECTOR (7 downto 0) := "00011100";
    constant ap_const_lv8_1A : STD_LOGIC_VECTOR (7 downto 0) := "00011010";
    constant ap_const_lv8_1E : STD_LOGIC_VECTOR (7 downto 0) := "00011110";
    constant ap_const_lv8_12 : STD_LOGIC_VECTOR (7 downto 0) := "00010010";
    constant ap_const_lv8_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_const_lv8_30 : STD_LOGIC_VECTOR (7 downto 0) := "00110000";
    constant ap_const_lv8_28 : STD_LOGIC_VECTOR (7 downto 0) := "00101000";
    constant ap_const_lv8_19 : STD_LOGIC_VECTOR (7 downto 0) := "00011001";
    constant ap_const_lv8_27 : STD_LOGIC_VECTOR (7 downto 0) := "00100111";
    constant ap_const_lv8_16 : STD_LOGIC_VECTOR (7 downto 0) := "00010110";
    constant ap_const_lv8_F : STD_LOGIC_VECTOR (7 downto 0) := "00001111";
    constant ap_const_lv8_E : STD_LOGIC_VECTOR (7 downto 0) := "00001110";
    constant ap_const_lv8_14 : STD_LOGIC_VECTOR (7 downto 0) := "00010100";
    constant ap_const_lv8_FA : STD_LOGIC_VECTOR (7 downto 0) := "11111010";
    constant ap_const_lv8_60 : STD_LOGIC_VECTOR (7 downto 0) := "01100000";
    constant ap_const_lv8_1F : STD_LOGIC_VECTOR (7 downto 0) := "00011111";
    constant ap_const_lv8_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal weights3_m_weights_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal weights3_m_weights_V_ce0 : STD_LOGIC;
    signal weights3_m_weights_V_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal weights3_m_weights_V_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal weights3_m_weights_V_1_ce0 : STD_LOGIC;
    signal weights3_m_weights_V_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal weights3_m_weights_V_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal weights3_m_weights_V_2_ce0 : STD_LOGIC;
    signal weights3_m_weights_V_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal weights3_m_weights_V_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal weights3_m_weights_V_3_ce0 : STD_LOGIC;
    signal weights3_m_weights_V_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal exitcond_flatten8_reg_1048 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_V_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal tmp_87_reg_1075 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_87_reg_1075_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten8_reg_277 : STD_LOGIC_VECTOR (22 downto 0);
    signal indvar_flatten_reg_288 : STD_LOGIC_VECTOR (11 downto 0);
    signal nm_reg_299 : STD_LOGIC_VECTOR (4 downto 0);
    signal sf_reg_310 : STD_LOGIC_VECTOR (6 downto 0);
    signal exitcond_flatten8_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exitcond_flatten8_reg_1048_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_next8_fu_359_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal nm_t_mid2_fu_453_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal nm_t_mid2_reg_1057 : STD_LOGIC_VECTOR (3 downto 0);
    signal nm_t_mid2_reg_1057_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal nm_t_mid2_reg_1057_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal nm_mid2_fu_461_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_78_fu_473_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_78_reg_1070 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_87_fu_479_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_87_reg_1075_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal sf_1_fu_485_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten_next_fu_497_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_V_53_reg_1089 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_83_reg_1114 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_86_fu_567_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_86_reg_1119 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_142_1_reg_1124 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_147_1_fu_625_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_147_1_reg_1129 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_142_2_reg_1134 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_147_2_fu_683_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_147_2_reg_1139 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_142_3_reg_1144 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_147_3_fu_741_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_147_3_reg_1149 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal tmp_79_fu_505_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal macRegisters_0_V_6_fu_196 : STD_LOGIC_VECTOR (7 downto 0);
    signal macRegisters_0_V_fu_767_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal macRegisters_1_V_6_fu_200 : STD_LOGIC_VECTOR (7 downto 0);
    signal macRegisters_1_V_fu_781_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal macRegisters_2_V_6_fu_204 : STD_LOGIC_VECTOR (7 downto 0);
    signal macRegisters_2_V_fu_795_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal macRegisters_3_V_6_fu_208 : STD_LOGIC_VECTOR (7 downto 0);
    signal macRegisters_3_V_fu_809_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_341_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond_flatten_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_75_fu_345_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_363_fu_401_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten_fu_395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal nm_mid_fu_371_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_76_mid_fu_407_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_364_fu_419_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal nm_1_fu_413_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_759_fu_433_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_75_mid1_fu_437_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_75_mid_fu_379_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal nm_t_mid_fu_387_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal sf_mid2_fu_425_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal sf_cast1_fu_469_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_75_mid2_fu_445_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal indvar_flatten_op_fu_491_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_81_fu_519_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_81_fu_519_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_071_assign_1_fu_512_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_81_fu_519_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_761_fu_543_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_760_fu_525_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s_fu_547_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_84_fu_553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_762_fu_559_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_140_1_fu_577_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_140_1_fu_577_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_140_1_fu_577_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_764_fu_601_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_763_fu_583_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_1_fu_605_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_143_1_fu_611_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_765_fu_617_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_140_2_fu_635_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_140_2_fu_635_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_140_2_fu_635_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_767_fu_659_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_766_fu_641_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_2_fu_663_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_143_2_fu_669_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_768_fu_675_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_140_3_fu_693_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_140_3_fu_693_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_140_3_fu_693_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_770_fu_717_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_769_fu_699_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_3_fu_721_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_143_3_fu_727_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_771_fu_733_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_147_cast_fu_759_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp1_fu_762_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_147_1_cast_fu_773_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp2_fu_776_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_147_2_cast_fu_787_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp3_fu_790_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_147_3_cast_fu_801_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp4_fu_804_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_835_p18 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_119_fu_878_p18 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_120_fu_921_p18 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_121_fu_964_p18 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_V_3_fu_1001_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_V_2_fu_958_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_V_1_fu_915_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_V_fu_872_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component computeS1_mux_164DeQ_x_x IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (7 downto 0);
        din9 : IN STD_LOGIC_VECTOR (7 downto 0);
        din10 : IN STD_LOGIC_VECTOR (7 downto 0);
        din11 : IN STD_LOGIC_VECTOR (7 downto 0);
        din12 : IN STD_LOGIC_VECTOR (7 downto 0);
        din13 : IN STD_LOGIC_VECTOR (7 downto 0);
        din14 : IN STD_LOGIC_VECTOR (7 downto 0);
        din15 : IN STD_LOGIC_VECTOR (7 downto 0);
        din16 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component Conv1DMac_new_weiKfY IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component Conv1DMac_new_weiLf8 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component Conv1DMac_new_weiMgi IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component Conv1DMac_new_weiNgs IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    weights3_m_weights_V_U : component Conv1DMac_new_weiKfY
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => weights3_m_weights_V_address0,
        ce0 => weights3_m_weights_V_ce0,
        q0 => weights3_m_weights_V_q0);

    weights3_m_weights_V_1_U : component Conv1DMac_new_weiLf8
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => weights3_m_weights_V_1_address0,
        ce0 => weights3_m_weights_V_1_ce0,
        q0 => weights3_m_weights_V_1_q0);

    weights3_m_weights_V_2_U : component Conv1DMac_new_weiMgi
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => weights3_m_weights_V_2_address0,
        ce0 => weights3_m_weights_V_2_ce0,
        q0 => weights3_m_weights_V_2_q0);

    weights3_m_weights_V_3_U : component Conv1DMac_new_weiNgs
    generic map (
        DataWidth => 8,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => weights3_m_weights_V_3_address0,
        ce0 => weights3_m_weights_V_3_ce0,
        q0 => weights3_m_weights_V_3_q0);

    computeS1_mux_164DeQ_x_x_U81 : component computeS1_mux_164DeQ_x_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => ap_const_lv8_21,
        din1 => ap_const_lv8_7,
        din2 => ap_const_lv8_1D,
        din3 => ap_const_lv8_25,
        din4 => ap_const_lv8_15,
        din5 => ap_const_lv8_9,
        din6 => ap_const_lv8_FC,
        din7 => ap_const_lv8_D,
        din8 => ap_const_lv8_8,
        din9 => ap_const_lv8_24,
        din10 => ap_const_lv8_6,
        din11 => ap_const_lv8_23,
        din12 => ap_const_lv8_A,
        din13 => ap_const_lv8_F5,
        din14 => ap_const_lv8_29,
        din15 => ap_const_lv8_44,
        din16 => nm_t_mid2_reg_1057_pp0_iter2_reg,
        dout => tmp_s_fu_835_p18);

    computeS1_mux_164DeQ_x_x_U82 : component computeS1_mux_164DeQ_x_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => ap_const_lv8_0,
        din1 => ap_const_lv8_0,
        din2 => ap_const_lv8_32,
        din3 => ap_const_lv8_0,
        din4 => ap_const_lv8_1B,
        din5 => ap_const_lv8_FE,
        din6 => ap_const_lv8_B,
        din7 => ap_const_lv8_C,
        din8 => ap_const_lv8_1C,
        din9 => ap_const_lv8_1A,
        din10 => ap_const_lv8_1E,
        din11 => ap_const_lv8_B,
        din12 => ap_const_lv8_12,
        din13 => ap_const_lv8_0,
        din14 => ap_const_lv8_4,
        din15 => ap_const_lv8_B,
        din16 => nm_t_mid2_reg_1057_pp0_iter2_reg,
        dout => tmp_119_fu_878_p18);

    computeS1_mux_164DeQ_x_x_U83 : component computeS1_mux_164DeQ_x_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => ap_const_lv8_30,
        din1 => ap_const_lv8_FC,
        din2 => ap_const_lv8_B,
        din3 => ap_const_lv8_4,
        din4 => ap_const_lv8_9,
        din5 => ap_const_lv8_28,
        din6 => ap_const_lv8_21,
        din7 => ap_const_lv8_19,
        din8 => ap_const_lv8_27,
        din9 => ap_const_lv8_0,
        din10 => ap_const_lv8_16,
        din11 => ap_const_lv8_B,
        din12 => ap_const_lv8_F,
        din13 => ap_const_lv8_D,
        din14 => ap_const_lv8_9,
        din15 => ap_const_lv8_E,
        din16 => nm_t_mid2_reg_1057_pp0_iter2_reg,
        dout => tmp_120_fu_921_p18);

    computeS1_mux_164DeQ_x_x_U84 : component computeS1_mux_164DeQ_x_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 4,
        dout_WIDTH => 8)
    port map (
        din0 => ap_const_lv8_12,
        din1 => ap_const_lv8_6,
        din2 => ap_const_lv8_14,
        din3 => ap_const_lv8_FA,
        din4 => ap_const_lv8_60,
        din5 => ap_const_lv8_FA,
        din6 => ap_const_lv8_A,
        din7 => ap_const_lv8_7,
        din8 => ap_const_lv8_12,
        din9 => ap_const_lv8_9,
        din10 => ap_const_lv8_1D,
        din11 => ap_const_lv8_1D,
        din12 => ap_const_lv8_1F,
        din13 => ap_const_lv8_1E,
        din14 => ap_const_lv8_5,
        din15 => ap_const_lv8_E,
        din16 => nm_t_mid2_reg_1057_pp0_iter2_reg,
        dout => tmp_121_fu_964_p18);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten8_reg_277_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten8_fu_353_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten8_reg_277 <= indvar_flatten_next8_fu_359_p2;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten8_reg_277 <= ap_const_lv23_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_288_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten8_fu_353_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_reg_288 <= indvar_flatten_next_fu_497_p3;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_reg_288 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;

    macRegisters_0_V_6_fu_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                macRegisters_0_V_6_fu_196 <= macRegisters_0_V_fu_767_p2;
            elsif ((((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                macRegisters_0_V_6_fu_196 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    macRegisters_1_V_6_fu_200_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                macRegisters_1_V_6_fu_200 <= macRegisters_1_V_fu_781_p2;
            elsif ((((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                macRegisters_1_V_6_fu_200 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    macRegisters_2_V_6_fu_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                macRegisters_2_V_6_fu_204 <= macRegisters_2_V_fu_795_p2;
            elsif ((((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                macRegisters_2_V_6_fu_204 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    macRegisters_3_V_6_fu_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                macRegisters_3_V_6_fu_208 <= macRegisters_3_V_fu_809_p2;
            elsif ((((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or (not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
                macRegisters_3_V_6_fu_208 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    nm_reg_299_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten8_fu_353_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                nm_reg_299 <= nm_mid2_fu_461_p3;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                nm_reg_299 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    sf_reg_310_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten8_fu_353_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                sf_reg_310 <= sf_1_fu_485_p2;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                sf_reg_310 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                exitcond_flatten8_reg_1048 <= exitcond_flatten8_fu_353_p2;
                exitcond_flatten8_reg_1048_pp0_iter1_reg <= exitcond_flatten8_reg_1048;
                nm_t_mid2_reg_1057_pp0_iter1_reg <= nm_t_mid2_reg_1057;
                tmp_87_reg_1075_pp0_iter1_reg <= tmp_87_reg_1075;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten8_fu_353_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                nm_t_mid2_reg_1057 <= nm_t_mid2_fu_453_p3;
                tmp_78_reg_1070 <= tmp_78_fu_473_p2;
                tmp_87_reg_1075 <= tmp_87_fu_479_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                nm_t_mid2_reg_1057_pp0_iter2_reg <= nm_t_mid2_reg_1057_pp0_iter1_reg;
                tmp_87_reg_1075_pp0_iter2_reg <= tmp_87_reg_1075_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten8_reg_1048_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_142_1_reg_1124 <= tmp_140_1_fu_577_p2(14 downto 7);
                tmp_142_2_reg_1134 <= tmp_140_2_fu_635_p2(14 downto 7);
                tmp_142_3_reg_1144 <= tmp_140_3_fu_693_p2(14 downto 7);
                tmp_147_1_reg_1129 <= tmp_147_1_fu_625_p2;
                tmp_147_2_reg_1139 <= tmp_147_2_fu_683_p2;
                tmp_147_3_reg_1149 <= tmp_147_3_fu_741_p2;
                tmp_83_reg_1114 <= tmp_81_fu_519_p2(14 downto 7);
                tmp_86_reg_1119 <= tmp_86_fu_567_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten8_reg_1048 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_V_53_reg_1089 <= in_V_V_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, exitcond_flatten8_fu_353_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((exitcond_flatten8_fu_353_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) and not(((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((exitcond_flatten8_fu_353_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state6 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter1, exitcond_flatten8_reg_1048, ap_enable_reg_pp0_iter3, tmp_87_reg_1075_pp0_iter2_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_1) and (out_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((exitcond_flatten8_reg_1048 = ap_const_lv1_0) and (in_V_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter1, exitcond_flatten8_reg_1048, ap_enable_reg_pp0_iter3, tmp_87_reg_1075_pp0_iter2_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_1) and (out_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((exitcond_flatten8_reg_1048 = ap_const_lv1_0) and (in_V_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(in_V_V_empty_n, out_V_V_full_n, ap_enable_reg_pp0_iter1, exitcond_flatten8_reg_1048, ap_enable_reg_pp0_iter3, tmp_87_reg_1075_pp0_iter2_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_1) and (out_V_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((exitcond_flatten8_reg_1048 = ap_const_lv1_0) and (in_V_V_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(in_V_V_empty_n, exitcond_flatten8_reg_1048)
    begin
                ap_block_state3_pp0_stage0_iter1 <= ((exitcond_flatten8_reg_1048 = ap_const_lv1_0) and (in_V_V_empty_n = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter3_assign_proc : process(out_V_V_full_n, tmp_87_reg_1075_pp0_iter2_reg)
    begin
                ap_block_state5_pp0_stage0_iter3 <= ((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_1) and (out_V_V_full_n = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(exitcond_flatten8_fu_353_p2)
    begin
        if ((exitcond_flatten8_fu_353_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    exitcond_flatten8_fu_353_p2 <= "1" when (indvar_flatten8_reg_277 = ap_const_lv23_400000) else "0";
    exitcond_flatten_fu_365_p2 <= "1" when (indvar_flatten_reg_288 = ap_const_lv12_400) else "0";

    in_V_V_blk_n_assign_proc : process(in_V_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_flatten8_reg_1048)
    begin
        if (((exitcond_flatten8_reg_1048 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_V_V_blk_n <= in_V_V_empty_n;
        else 
            in_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_V_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_flatten8_reg_1048, ap_block_pp0_stage0_11001)
    begin
        if (((exitcond_flatten8_reg_1048 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            in_V_V_read <= ap_const_logic_1;
        else 
            in_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    indvar_flatten_next8_fu_359_p2 <= std_logic_vector(unsigned(ap_const_lv23_1) + unsigned(indvar_flatten8_reg_277));
    indvar_flatten_next_fu_497_p3 <= 
        ap_const_lv12_1 when (exitcond_flatten_fu_365_p2(0) = '1') else 
        indvar_flatten_op_fu_491_p2;
    indvar_flatten_op_fu_491_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_288) + unsigned(ap_const_lv12_1));

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    macRegisters_0_V_fu_767_p2 <= std_logic_vector(unsigned(macRegisters_0_V_6_fu_196) + unsigned(tmp1_fu_762_p2));
    macRegisters_1_V_fu_781_p2 <= std_logic_vector(unsigned(macRegisters_1_V_6_fu_200) + unsigned(tmp2_fu_776_p2));
    macRegisters_2_V_fu_795_p2 <= std_logic_vector(unsigned(macRegisters_2_V_6_fu_204) + unsigned(tmp3_fu_790_p2));
    macRegisters_3_V_fu_809_p2 <= std_logic_vector(unsigned(macRegisters_3_V_6_fu_208) + unsigned(tmp4_fu_804_p2));
    nm_1_fu_413_p2 <= std_logic_vector(unsigned(ap_const_lv5_1) + unsigned(nm_mid_fu_371_p3));
    nm_mid2_fu_461_p3 <= 
        nm_1_fu_413_p2 when (tmp_76_mid_fu_407_p2(0) = '1') else 
        nm_mid_fu_371_p3;
    nm_mid_fu_371_p3 <= 
        ap_const_lv5_0 when (exitcond_flatten_fu_365_p2(0) = '1') else 
        nm_reg_299;
    nm_t_mid2_fu_453_p3 <= 
        tmp_759_fu_433_p1 when (tmp_76_mid_fu_407_p2(0) = '1') else 
        nm_t_mid_fu_387_p3;
    nm_t_mid_fu_387_p3 <= 
        ap_const_lv4_0 when (exitcond_flatten_fu_365_p2(0) = '1') else 
        tmp_fu_341_p1;
    not_exitcond_flatten_fu_395_p2 <= (exitcond_flatten_fu_365_p2 xor ap_const_lv1_1);

    out_V_V_blk_n_assign_proc : process(out_V_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter3, tmp_87_reg_1075_pp0_iter2_reg)
    begin
        if (((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            out_V_V_blk_n <= out_V_V_full_n;
        else 
            out_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_V_V_din <= (((result_V_3_fu_1001_p2 & result_V_2_fu_958_p2) & result_V_1_fu_915_p2) & result_V_fu_872_p2);

    out_V_V_write_assign_proc : process(ap_enable_reg_pp0_iter3, tmp_87_reg_1075_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((tmp_87_reg_1075_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            out_V_V_write <= ap_const_logic_1;
        else 
            out_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

        p_071_assign_1_fu_512_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_V_53_reg_1089),16));

    p_1_fu_605_p2 <= "0" when (tmp_764_fu_601_p1 = ap_const_lv6_0) else "1";
    p_2_fu_663_p2 <= "0" when (tmp_767_fu_659_p1 = ap_const_lv6_0) else "1";
    p_3_fu_721_p2 <= "0" when (tmp_770_fu_717_p1 = ap_const_lv6_0) else "1";
    p_s_fu_547_p2 <= "0" when (tmp_761_fu_543_p1 = ap_const_lv6_0) else "1";

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    result_V_1_fu_915_p2 <= std_logic_vector(unsigned(macRegisters_1_V_fu_781_p2) + unsigned(tmp_119_fu_878_p18));
    result_V_2_fu_958_p2 <= std_logic_vector(unsigned(macRegisters_2_V_fu_795_p2) + unsigned(tmp_120_fu_921_p18));
    result_V_3_fu_1001_p2 <= std_logic_vector(unsigned(macRegisters_3_V_fu_809_p2) + unsigned(tmp_121_fu_964_p18));
    result_V_fu_872_p2 <= std_logic_vector(unsigned(macRegisters_0_V_fu_767_p2) + unsigned(tmp_s_fu_835_p18));
    sf_1_fu_485_p2 <= std_logic_vector(unsigned(sf_mid2_fu_425_p3) + unsigned(ap_const_lv7_1));
    sf_cast1_fu_469_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sf_mid2_fu_425_p3),10));
    sf_mid2_fu_425_p3 <= 
        ap_const_lv7_0 when (tmp_364_fu_419_p2(0) = '1') else 
        sf_reg_310;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp1_fu_762_p2 <= std_logic_vector(unsigned(tmp_147_cast_fu_759_p1) + unsigned(tmp_83_reg_1114));
    tmp2_fu_776_p2 <= std_logic_vector(unsigned(tmp_147_1_cast_fu_773_p1) + unsigned(tmp_142_1_reg_1124));
    tmp3_fu_790_p2 <= std_logic_vector(unsigned(tmp_147_2_cast_fu_787_p1) + unsigned(tmp_142_2_reg_1134));
    tmp4_fu_804_p2 <= std_logic_vector(unsigned(tmp_147_3_cast_fu_801_p1) + unsigned(tmp_142_3_reg_1144));
    tmp_140_1_fu_577_p0 <= weights3_m_weights_V_1_q0;
    tmp_140_1_fu_577_p1 <= p_071_assign_1_fu_512_p1(8 - 1 downto 0);
    tmp_140_1_fu_577_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(tmp_140_1_fu_577_p0) * signed(tmp_140_1_fu_577_p1))), 16));
    tmp_140_2_fu_635_p0 <= weights3_m_weights_V_2_q0;
    tmp_140_2_fu_635_p1 <= p_071_assign_1_fu_512_p1(8 - 1 downto 0);
    tmp_140_2_fu_635_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(tmp_140_2_fu_635_p0) * signed(tmp_140_2_fu_635_p1))), 16));
    tmp_140_3_fu_693_p0 <= weights3_m_weights_V_3_q0;
    tmp_140_3_fu_693_p1 <= p_071_assign_1_fu_512_p1(8 - 1 downto 0);
    tmp_140_3_fu_693_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(tmp_140_3_fu_693_p0) * signed(tmp_140_3_fu_693_p1))), 16));
    tmp_143_1_fu_611_p2 <= (tmp_763_fu_583_p3 or p_1_fu_605_p2);
    tmp_143_2_fu_669_p2 <= (tmp_766_fu_641_p3 or p_2_fu_663_p2);
    tmp_143_3_fu_727_p2 <= (tmp_769_fu_699_p3 or p_3_fu_721_p2);
    tmp_147_1_cast_fu_773_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_147_1_reg_1129),8));
    tmp_147_1_fu_625_p2 <= (tmp_765_fu_617_p3 and tmp_143_1_fu_611_p2);
    tmp_147_2_cast_fu_787_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_147_2_reg_1139),8));
    tmp_147_2_fu_683_p2 <= (tmp_768_fu_675_p3 and tmp_143_2_fu_669_p2);
    tmp_147_3_cast_fu_801_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_147_3_reg_1149),8));
    tmp_147_3_fu_741_p2 <= (tmp_771_fu_733_p3 and tmp_143_3_fu_727_p2);
    tmp_147_cast_fu_759_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_86_reg_1119),8));
    tmp_363_fu_401_p2 <= "1" when (sf_reg_310 = ap_const_lv7_40) else "0";
    tmp_364_fu_419_p2 <= (tmp_76_mid_fu_407_p2 or exitcond_flatten_fu_365_p2);
    tmp_759_fu_433_p1 <= nm_1_fu_413_p2(4 - 1 downto 0);
    tmp_75_fu_345_p3 <= (tmp_fu_341_p1 & ap_const_lv6_0);
    tmp_75_mid1_fu_437_p3 <= (tmp_759_fu_433_p1 & ap_const_lv6_0);
    tmp_75_mid2_fu_445_p3 <= 
        tmp_75_mid1_fu_437_p3 when (tmp_76_mid_fu_407_p2(0) = '1') else 
        tmp_75_mid_fu_379_p3;
    tmp_75_mid_fu_379_p3 <= 
        ap_const_lv10_0 when (exitcond_flatten_fu_365_p2(0) = '1') else 
        tmp_75_fu_345_p3;
    tmp_760_fu_525_p3 <= tmp_81_fu_519_p2(14 downto 14);
    tmp_761_fu_543_p1 <= tmp_81_fu_519_p2(6 - 1 downto 0);
    tmp_762_fu_559_p3 <= tmp_81_fu_519_p2(6 downto 6);
    tmp_763_fu_583_p3 <= tmp_140_1_fu_577_p2(14 downto 14);
    tmp_764_fu_601_p1 <= tmp_140_1_fu_577_p2(6 - 1 downto 0);
    tmp_765_fu_617_p3 <= tmp_140_1_fu_577_p2(6 downto 6);
    tmp_766_fu_641_p3 <= tmp_140_2_fu_635_p2(14 downto 14);
    tmp_767_fu_659_p1 <= tmp_140_2_fu_635_p2(6 - 1 downto 0);
    tmp_768_fu_675_p3 <= tmp_140_2_fu_635_p2(6 downto 6);
    tmp_769_fu_699_p3 <= tmp_140_3_fu_693_p2(14 downto 14);
    tmp_76_mid_fu_407_p2 <= (tmp_363_fu_401_p2 and not_exitcond_flatten_fu_395_p2);
    tmp_770_fu_717_p1 <= tmp_140_3_fu_693_p2(6 - 1 downto 0);
    tmp_771_fu_733_p3 <= tmp_140_3_fu_693_p2(6 downto 6);
    tmp_78_fu_473_p2 <= std_logic_vector(unsigned(sf_cast1_fu_469_p1) + unsigned(tmp_75_mid2_fu_445_p3));
    tmp_79_fu_505_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_78_reg_1070),64));
    tmp_81_fu_519_p0 <= weights3_m_weights_V_q0;
    tmp_81_fu_519_p1 <= p_071_assign_1_fu_512_p1(8 - 1 downto 0);
    tmp_81_fu_519_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(tmp_81_fu_519_p0) * signed(tmp_81_fu_519_p1))), 16));
    tmp_84_fu_553_p2 <= (tmp_760_fu_525_p3 or p_s_fu_547_p2);
    tmp_86_fu_567_p2 <= (tmp_84_fu_553_p2 and tmp_762_fu_559_p3);
    tmp_87_fu_479_p2 <= "1" when (sf_mid2_fu_425_p3 = ap_const_lv7_3F) else "0";
    tmp_fu_341_p1 <= nm_reg_299(4 - 1 downto 0);
    weights3_m_weights_V_1_address0 <= tmp_79_fu_505_p1(10 - 1 downto 0);

    weights3_m_weights_V_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            weights3_m_weights_V_1_ce0 <= ap_const_logic_1;
        else 
            weights3_m_weights_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    weights3_m_weights_V_2_address0 <= tmp_79_fu_505_p1(10 - 1 downto 0);

    weights3_m_weights_V_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            weights3_m_weights_V_2_ce0 <= ap_const_logic_1;
        else 
            weights3_m_weights_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    weights3_m_weights_V_3_address0 <= tmp_79_fu_505_p1(10 - 1 downto 0);

    weights3_m_weights_V_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            weights3_m_weights_V_3_ce0 <= ap_const_logic_1;
        else 
            weights3_m_weights_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    weights3_m_weights_V_address0 <= tmp_79_fu_505_p1(10 - 1 downto 0);

    weights3_m_weights_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            weights3_m_weights_V_ce0 <= ap_const_logic_1;
        else 
            weights3_m_weights_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
